// ============================================================
// TAMARIU CHALET — Booking Availability
// ============================================================
// Auto-generated by sync-bookings.py on 2026-07-19 13:42
// To regenerate:  python3 sync-bookings.py
// Manual entries: add to the arrays below and upload the file.
//
// DATE FORMAT: "YYYY-MM-DD"
// from = check-in · to = check-out · note = your reference
// ============================================================

const BOOKINGS = {
  'double-room': [
    { from: '2026-07-19', to: '2026-07-24', note: 'Reserved' },
    { from: '2026-08-02', to: '2026-08-09', note: 'Reserved' },
    { from: '2026-08-10', to: '2026-08-14', note: 'Reserved' },
    { from: '2026-08-15', to: '2026-08-20', note: 'Reserved' },
    { from: '2026-08-23', to: '2026-08-28', note: 'Reserved' },
    { from: '2026-09-01', to: '2026-09-28', note: 'Airbnb (Not available)' },
    { from: '2027-07-19', to: '2027-07-20', note: 'Airbnb (Not available)' },
  ],

  'twin-room-1': [
    { from: '2026-07-24', to: '2026-07-29', note: 'Reserved' },
    { from: '2026-08-04', to: '2026-08-11', note: 'Reserved' },
    { from: '2026-08-11', to: '2026-08-14', note: 'Airbnb (Not available)' },
    { from: '2026-08-16', to: '2026-08-21', note: 'Reserved' },
    { from: '2026-09-01', to: '2026-09-28', note: 'Airbnb (Not available)' },
    { from: '2027-07-19', to: '2027-07-20', note: 'Airbnb (Not available)' },
  ],

  'twin-room-2': [
    { from: '2026-07-19', to: '2026-07-21', note: 'Reserved' },
    { from: '2026-07-21', to: '2026-07-24', note: 'Airbnb (Not available)' },
    { from: '2026-07-24', to: '2026-07-27', note: 'Reserved' },
    { from: '2026-08-02', to: '2026-08-05', note: 'Reserved' },
    { from: '2026-08-05', to: '2026-08-09', note: 'Reserved' },
    { from: '2026-08-09', to: '2026-08-13', note: 'Reserved' },
    { from: '2026-08-13', to: '2026-08-21', note: 'Reserved' },
    { from: '2026-09-01', to: '2026-09-28', note: 'Airbnb (Not available)' },
    { from: '2027-07-19', to: '2027-07-20', note: 'Airbnb (Not available)' },
  ],

  'studio-apartment': [
    { from: '2026-07-19', to: '2026-07-26', note: 'Reserved' },
    { from: '2026-07-26', to: '2026-08-02', note: 'Reserved' },
    { from: '2026-08-02', to: '2026-08-06', note: 'Reserved' },
    { from: '2026-08-07', to: '2026-08-14', note: 'Airbnb (Not available)' },
    { from: '2026-08-15', to: '2026-08-20', note: 'Reserved' },
    { from: '2026-08-28', to: '2026-09-01', note: 'Reserved' },
    { from: '2026-09-01', to: '2026-09-28', note: 'Airbnb (Not available)' },
    { from: '2027-07-19', to: '2027-07-20', note: 'Airbnb (Not available)' },
  ],

};

// ── DO NOT EDIT BELOW THIS LINE ─────────────────────────────
function isRoomAvailable(roomKey, checkIn, checkOut) {
  const bookings = BOOKINGS[roomKey];
  if (!bookings || bookings.length === 0) return true;
  const d1 = new Date(checkIn);
  const d2 = new Date(checkOut);
  return !bookings.some(b => d1 < new Date(b.to) && d2 > new Date(b.from));
}
