#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate sitemap.xml from what is actually on disk.

The sitemap was previously hand-maintained and had drifted: 43 live pages were
missing from it. Generating it from the filesystem means adding a page can no
longer silently leave it unindexed.

Each entry carries xhtml:link alternates mirroring the page's hreflang block,
which is what Google asks for on multilingual sites.

    python3 notes/scripts/build_sitemap.py           # dry run (prints a diff)
    python3 notes/scripts/build_sitemap.py --apply
"""

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = "https://tamariuchalet.com"
LANGS = ["en", "es", "ca", "fr", "nl"]
TRANSLATED = ["es", "ca", "fr", "nl"]
SKIP_DIRS = {"notes", ".github", ".git", ".well-known"}

# section -> (changefreq, priority for English, priority for translations)
RULES = [
    ("index.html",        ("weekly",  "1.0", "0.9")),
    ("accommodation/",    ("monthly", "0.9", "0.8")),
    ("contact/",          ("monthly", "0.8", "0.7")),
    ("availability/",     ("weekly",  "0.8", "0.7")),
    ("Reviews/",          ("monthly", "0.7", "0.6")),
    ("getting-here/",     ("yearly",  "0.6", "0.5")),
    ("things-to-do/",     ("yearly",  "0.6", "0.5")),
    ("about-catalunya/",  ("yearly",  "0.6", "0.5")),
]
DEFAULT = ("yearly", "0.5", "0.4")

SECTION_TITLES = {
    "index.html": "Home",
    "accommodation/": "Accommodation",
    "availability/": "Availability",
    "contact/": "Contact",
    "getting-here/": "Getting Here",
    "things-to-do/": "Things To Do",
    "about-catalunya/": "About Catalunya",
    "Reviews/": "Reviews",
}


def logical(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    parts = rel.split("/")
    return "/".join(parts[1:]) if parts[0] in TRANSLATED else rel


def lang_of(path: Path) -> str:
    first = path.relative_to(ROOT).parts[0]
    return first if first in TRANSLATED else "en"


def url_for(lang: str, log: str) -> str:
    p = "" if log == "index.html" else log
    if p.endswith("/index.html"):
        p = p[: -len("index.html")]
    prefix = "" if lang == "en" else f"/{lang}"
    return f"{BASE}{prefix}/{p}"


def rule_for(log: str):
    for prefix, vals in RULES:
        if log == prefix or log.startswith(prefix):
            return prefix, vals
    return None, DEFAULT


def lastmod(path: Path) -> str:
    """Git commit date of the file, falling back to today for new files."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(path.relative_to(ROOT))],
            cwd=ROOT, capture_output=True, text=True, timeout=15,
        )
        stamp = out.stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", stamp):
            return stamp
    except Exception:
        pass
    return date.today().isoformat()


def site_pages():
    for p in sorted(ROOT.rglob("*.html")):
        if p.relative_to(ROOT).parts[0] in SKIP_DIRS:
            continue
        if 'name="robots" content="noindex' in p.read_text(encoding="utf-8"):
            continue
        yield p


def build() -> str:
    # group pages by logical path so alternates can be emitted together
    groups: dict[str, dict[str, Path]] = {}
    for p in site_pages():
        groups.setdefault(logical(p), {})[lang_of(p)] = p

    # availability/ self-translates via ?lang= and is a single URL
    single = {"availability/index.html"}

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
           "",
           "  <!-- Generated by notes/scripts/build_sitemap.py — do not hand-edit. -->",
           "  <!-- Re-run after adding or removing any page. -->",
           ""]

    current_section = object()
    for log in sorted(groups, key=lambda l: (rule_for(l)[0] or "zz", l)):
        section, (freq, pri_en, pri_tr) = rule_for(log)
        if section != current_section:
            current_section = section
            title = SECTION_TITLES.get(section, "Other")
            out.append(f"  <!-- {title} -->")

        langs = groups[log]
        emit = ["en"] if log in single else [l for l in LANGS if l in langs]
        for lang in emit:
            page = langs[lang]
            url = url_for(lang, log)
            pri = pri_en if lang == "en" else pri_tr
            entry = [f"  <url><loc>{url}</loc>"]
            entry.append(f"<lastmod>{lastmod(page)}</lastmod>")
            entry.append(f"<changefreq>{freq}</changefreq><priority>{pri}</priority>")
            if len(emit) > 1:
                for alt in emit:
                    entry.append(
                        f'\n    <xhtml:link rel="alternate" hreflang="{alt}" '
                        f'href="{url_for(alt, log)}"/>'
                    )
                entry.append(
                    f'\n    <xhtml:link rel="alternate" hreflang="x-default" '
                    f'href="{url_for("en", log)}"/>\n  '
                )
            entry.append("</url>")
            out.append("".join(entry))
        out.append("")

    out.append("</urlset>")
    return "\n".join(out) + "\n"


def main():
    apply = "--apply" in sys.argv
    new = build()
    target = ROOT / "sitemap.xml"
    old = target.read_text(encoding="utf-8") if target.exists() else ""
    old_n = len(re.findall(r"<loc>", old))
    new_n = len(re.findall(r"<loc>", new))
    if apply:
        target.write_text(new, encoding="utf-8")
        print(f"sitemap.xml written: {old_n} -> {new_n} URLs")
    else:
        print(f"would write sitemap.xml: {old_n} -> {new_n} URLs (dry run)")


if __name__ == "__main__":
    main()
