#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Short labels for things-to-do/local-beaches.html.

Split from the prose (content_beaches.py) purely for readability — the beach
cards reuse the same field labels twelve times over, so they are collected here
once. Beach names, restaurant names, street names and Catalan dish names are
deliberately absent, which leaves them untranslated.
"""


def T(es, ca, fr, nl):
    return {"es": es, "ca": ca, "fr": fr, "nl": nl}


LABELS = {
    # ── page chrome ──────────────────────────────────────────────────────
    "Things To Do → Local Beaches": T(
        "Qué Hacer → Playas Locales", "Què Fer → Platges Locals",
        "À Faire → Plages Locales", "Wat Te Doen → Lokale Stranden"),
    "Local Beaches &amp; Coves": T(
        "Playas y Calas Locales", "Platges i Cales Locals",
        "Plages &amp; Criques Locales", "Lokale Stranden &amp; Baaien"),
    "Jump to a beach": T("Ir a una playa", "Vés a una platja",
                         "Aller à une plage", "Ga naar een strand"),

    # ── section headers ──────────────────────────────────────────────────
    "Walking Distance": T("A Pie", "A Peu", "À Pied", "Op Loopafstand"),
    "On the Doorstep": T("A Un Paso", "A Tocar", "À Deux Pas", "Vlakbij"),
    "5–15 Minutes by Car": T("5–15 Minutos en Coche", "5–15 Minuts en Cotxe",
                             "5–15 Minutes en Voiture", "5–15 Minuten met de Auto"),
    "15–25 Minutes by Car": T("15–25 Minutos en Coche", "15–25 Minuts en Cotxe",
                              "15–25 Minutes en Voiture", "15–25 Minuten met de Auto"),
    "25–30 Minutes by Car": T("25–30 Minutos en Coche", "25–30 Minuts en Cotxe",
                              "25–30 Minutes en Voiture", "25–30 Minuten met de Auto"),
    "The Palafrugell Coast": T("La Costa de Palafrugell", "La Costa de Palafrugell",
                               "La Côte de Palafrugell", "De Kust van Palafrugell"),
    "The Begur Coves": T("Las Calas de Begur", "Les Cales de Begur",
                         "Les Criques de Begur", "De Baaien van Begur"),
    "The Long Sands": T("Las Playas Largas", "Les Platges Llargues",
                        "Les Grandes Plages", "De Lange Zandstranden"),

    # ── beach card subtitles ─────────────────────────────────────────────
    "Our Home Beach": T("Nuestra Playa", "La Nostra Platja",
                        "Notre Plage", "Ons Eigen Strand"),
    "Hidden Cove · No Road Access": T(
        "Cala Escondida · Sin Acceso Rodado", "Cala Amagada · Sense Accés Rodat",
        "Crique Cachée · Sans Accès Routier", "Verborgen Baai · Niet Bereikbaar met de Auto"),
    "The Famous Turquoise Bay": T(
        "La Famosa Bahía Turquesa", "La Famosa Badia Turquesa",
        "La Célèbre Baie Turquoise", "De Beroemde Turquoise Baai"),
    "Tiny Cove · Locals' Secret": T(
        "Cala Diminuta · Secreto Local", "Cala Diminuta · Secret Local",
        "Crique Minuscule · Secret des Locaux", "Piepkleine Baai · Geheim van de Locals"),
    "Elegant Promenade · Sailing": T(
        "Paseo Elegante · Vela", "Passeig Elegant · Vela",
        "Promenade Élégante · Voile", "Elegante Boulevard · Zeilen"),
    "Postcard Fishing Village": T(
        "Pueblo Pesquero de Postal", "Poble Pescador de Postal",
        "Village de Pêcheurs de Carte Postale", "Vissersdorp als een Ansichtkaart"),
    "Wild Cove Below Cap Roig": T(
        "Cala Salvaje bajo Cap Roig", "Cala Salvatge sota Cap Roig",
        "Crique Sauvage sous Cap Roig", "Wilde Baai onder Cap Roig"),
    "Begur's Largest Beach": T(
        "La Playa Más Grande de Begur", "La Platja Més Gran de Begur",
        "La Plus Grande Plage de Begur", "Het Grootste Strand van Begur"),
    "Small, Perfect, Pebbly": T(
        "Pequeña, Perfecta, de Cantos", "Petita, Perfecta, de Còdols",
        "Petite, Parfaite, de Galets", "Klein, Perfect, Kiezelstrand"),
    "Wide Open Sand · Windsurfing": T(
        "Arena Abierta · Windsurf", "Sorra Oberta · Windsurf",
        "Grand Sable Ouvert · Planche à Voile", "Wijd Open Zand · Windsurfen"),
    "The Last Undeveloped Beach": T(
        "La Última Playa Sin Urbanizar", "L'Última Platja Sense Urbanitzar",
        "La Dernière Plage Non Bâtie", "Het Laatste Onbebouwde Strand"),
    "Shallow, Calm, Great for Children": T(
        "Poco Profunda, Tranquila, Ideal para Niños",
        "Poc Profunda, Tranquil·la, Ideal per a Nens",
        "Peu Profonde, Calme, Idéale pour les Enfants",
        "Ondiep, Rustig, Ideaal voor Kinderen"),

    # ── beach descriptors ────────────────────────────────────────────────
    "Palafrugell · Blue Flag · fine sand": T(
        "Palafrugell · Bandera Azul · arena fina", "Palafrugell · Bandera Blava · sorra fina",
        "Palafrugell · Pavillon Bleu · sable fin", "Palafrugell · Blauwe Vlag · fijn zand"),
    "Palafrugell · Blue Flag · fine golden sand": T(
        "Palafrugell · Bandera Azul · arena dorada fina",
        "Palafrugell · Bandera Blava · sorra daurada fina",
        "Palafrugell · Pavillon Bleu · sable doré fin",
        "Palafrugell · Blauwe Vlag · fijn goudkleurig zand"),
    "Palafrugell · pebble &amp; shingle": T(
        "Palafrugell · cantos y grava", "Palafrugell · còdols i grava",
        "Palafrugell · galets et gravier", "Palafrugell · kiezels en grind"),
    "Begur · fine white sand · includes Fornells &amp; Platgeta": T(
        "Begur · arena blanca fina · incluye Fornells y Platgeta",
        "Begur · sorra blanca fina · inclou Fornells i Platgeta",
        "Begur · sable blanc fin · comprend Fornells &amp; Platgeta",
        "Begur · fijn wit zand · inclusief Fornells &amp; Platgeta"),
    "Tamariu, Palafrugell · pebble &amp; rock platforms": T(
        "Tamariu, Palafrugell · cantos y plataformas de roca",
        "Tamariu, Palafrugell · còdols i plataformes de roca",
        "Tamariu, Palafrugell · galets et plateformes rocheuses",
        "Tamariu, Palafrugell · kiezels en rotsplateaus"),
    "Palafrugell · several small coves — Port Bo, El Canadell, Port Pelegrí": T(
        "Palafrugell · varias calas pequeñas — Port Bo, El Canadell, Port Pelegrí",
        "Palafrugell · diverses cales petites — Port Bo, El Canadell, Port Pelegrí",
        "Palafrugell · plusieurs petites criques — Port Bo, El Canadell, Port Pelegrí",
        "Palafrugell · meerdere kleine baaien — Port Bo, El Canadell, Port Pelegrí"),
    "Calella de Palafrugell · coarse sand &amp; shingle": T(
        "Calella de Palafrugell · arena gruesa y grava",
        "Calella de Palafrugell · sorra gruixuda i grava",
        "Calella de Palafrugell · sable grossier et gravier",
        "Calella de Palafrugell · grof zand en grind"),
    "Begur · sand &amp; shingle": T(
        "Begur · arena y grava", "Begur · sorra i grava",
        "Begur · sable et gravier", "Begur · zand en grind"),
    "Begur · pebble &amp; shingle": T(
        "Begur · cantos y grava", "Begur · còdols i grava",
        "Begur · galets et gravier", "Begur · kiezels en grind"),
    "Pals · ~3 km of fine golden sand": T(
        "Pals · ~3 km de arena dorada fina", "Pals · ~3 km de sorra daurada fina",
        "Pals · ~3 km de sable doré fin", "Pals · ~3 km fijn goudkleurig zand"),
    "Palamós · fine sand · protected natural area": T(
        "Palamós · arena fina · espacio natural protegido",
        "Palamós · sorra fina · espai natural protegit",
        "Palamós · sable fin · espace naturel protégé",
        "Palamós · fijn zand · beschermd natuurgebied"),
    "Palamós · fine sand": T("Palamós · arena fina", "Palamós · sorra fina",
                             "Palamós · sable fin", "Palamós · fijn zand"),

    # ── field labels ─────────────────────────────────────────────────────
    "From the chalet": T("Desde la casa", "Des de la casa",
                         "Depuis la maison", "Vanaf het huis"),
    "From Tamariu": T("Desde Tamariu", "Des de Tamariu",
                      "Depuis Tamariu", "Vanaf Tamariu"),
    "By car": T("En coche", "En cotxe", "En voiture", "Met de auto"),
    "On foot": T("A pie", "A peu", "À pied", "Te voet"),
    "Walking time": T("Tiempo a pie", "Temps a peu",
                      "Temps de marche", "Looptijd"),
    "Coastal walk": T("Camino de ronda", "Camí de ronda",
                      "Chemin côtier", "Kustpad"),
    "Coastal walk from Llafranc": T(
        "Camino de ronda desde Llafranc", "Camí de ronda des de Llafranc",
        "Chemin côtier depuis Llafranc", "Kustpad vanaf Llafranc"),
    "Walk from Calella": T("A pie desde Calella", "A peu des de Calella",
                           "À pied depuis Calella", "Te voet vanaf Calella"),
    "Walk to Illa Roja": T("A pie hasta Illa Roja", "A peu fins a Illa Roja",
                           "À pied jusqu'à Illa Roja", "Te voet naar Illa Roja"),
    "Walk to Aiguafreda": T("A pie hasta Aiguafreda", "A peu fins a Aiguafreda",
                            "À pied jusqu'à Aiguafreda", "Te voet naar Aiguafreda"),
    "Parking": T("Aparcamiento", "Aparcament", "Stationnement", "Parkeren"),
    "Parking nearby": T("Aparcamiento cerca", "Aparcament a prop",
                        "Stationnement à proximité", "Parkeren in de buurt"),
    "Where to eat": T("Dónde comer", "On menjar", "Où manger", "Waar te eten"),
    "Best for": T("Ideal para", "Ideal per a", "Idéal pour", "Het best voor"),
    "Distance": T("Distancia", "Distància", "Distance", "Afstand"),
    "Type": T("Tipo", "Tipus", "Type", "Type"),
    "Beach": T("Playa", "Platja", "Plage", "Strand"),
    "At a Glance": T("De Un Vistazo", "D'Un Cop d'Ull",
                     "En Bref", "In Één Oogopslag"),
    "Distances &amp; Best For": T(
        "Distancias y Para Qué Van Bien", "Distàncies i Per a Què Van Bé",
        "Distances &amp; Idéales Pour", "Afstanden &amp; Waarvoor Geschikt"),
    "Free option:": T("Opción gratuita:", "Opció gratuïta:",
                      "Option gratuite :", "Gratis optie:"),
    "Nearest free option:": T(
        "Opción gratuita más cercana:", "Opció gratuïta més propera:",
        "Option gratuite la plus proche :", "Dichtstbijzijnde gratis optie:"),
    "Alternative:": T("Alternativa:", "Alternativa:",
                      "Autre solution :", "Alternatief:"),
    "A note on parking:": T("Nota sobre el aparcamiento:", "Nota sobre l'aparcament:",
                            "À propos du stationnement :", "Over parkeren:"),
    "Ask us:": T("Pregúntenos:", "Pregunteu-nos:",
                 "Demandez-nous :", "Vraag ons:"),
    "Back in Tamariu": T("De vuelta en Tamariu", "De tornada a Tamariu",
                         "De retour à Tamariu", "Terug in Tamariu"),

    # ── amenity tags ─────────────────────────────────────────────────────
    "Family-friendly": T("Ideal para familias", "Ideal per a famílies",
                         "Familial", "Gezinsvriendelijk"),
    "Snorkelling": T("Snorkel", "Snorkel", "Snorkeling", "Snorkelen"),
    "Excellent snorkelling": T("Snorkel excelente", "Snorkel excel·lent",
                               "Snorkeling excellent", "Uitstekend snorkelen"),
    "Snorkelling, solitude": T("Snorkel y soledad", "Snorkel i solitud",
                               "Snorkeling et tranquillité", "Snorkelen, afzondering"),
    "Restaurants on the sand": T(
        "Restaurantes en la arena", "Restaurants a la sorra",
        "Restaurants sur le sable", "Restaurants op het zand"),
    "Restaurants on the water": T(
        "Restaurantes junto al agua", "Restaurants arran d'aigua",
        "Restaurants au bord de l'eau", "Restaurants aan het water"),
    "Restaurants on the seafront": T(
        "Restaurantes en el paseo marítimo", "Restaurants al passeig marítim",
        "Restaurants sur le front de mer", "Restaurants aan de boulevard"),
    "Kayak hire": T("Alquiler de kayaks", "Lloguer de caiacs",
                    "Location de kayaks", "Kajakverhuur"),
    "Kayak school": T("Escuela de kayak", "Escola de caiac",
                      "École de kayak", "Kajakschool"),
    "Lifeguard in season": T("Socorrista en temporada", "Socorrista en temporada",
                             "Surveillance en saison", "Strandwacht in het seizoen"),
    "Turquoise water": T("Agua turquesa", "Aigua turquesa",
                         "Eau turquoise", "Turquoise water"),
    "Turquoise water, boat trips": T(
        "Agua turquesa, paseos en barco", "Aigua turquesa, passejades en barca",
        "Eau turquoise, sorties en bateau", "Turquoise water, boottochten"),
    "Calm &amp; shallow": T("Tranquila y poco profunda", "Tranquil·la i poc profunda",
                            "Calme &amp; peu profonde", "Rustig &amp; ondiep"),
    "Boat trips": T("Paseos en barco", "Passejades en barca",
                    "Sorties en bateau", "Boottochten"),
    "Busy in August": T("Concurrida en agosto", "Concorreguda a l'agost",
                        "Fréquentée en août", "Druk in augustus"),
    "Diving": T("Buceo", "Submarinisme", "Plongée", "Duiken"),
    "Quiet": T("Tranquila", "Tranquil·la", "Tranquille", "Rustig"),
    "Very quiet": T("Muy tranquila", "Molt tranquil·la",
                    "Très tranquille", "Heel rustig"),
    "Rock swimming": T("Baño desde las rocas", "Bany des de les roques",
                       "Baignade depuis les rochers", "Zwemmen vanaf de rotsen"),
    "No facilities": T("Sin servicios", "Sense serveis",
                       "Aucun service", "Geen voorzieningen"),
    "Foot access only": T("Solo acceso a pie", "Només accés a peu",
                          "Accès à pied uniquement", "Alleen te voet bereikbaar"),
    "Steep final descent": T("Bajada final empinada", "Baixada final costeruda",
                             "Descente finale raide", "Steile laatste afdaling"),
    "Steps down": T("Escaleras de bajada", "Escales de baixada",
                    "Escalier pour descendre", "Trappen naar beneden"),
    "Bring water": T("Lleve agua", "Porteu aigua",
                     "Emportez de l'eau", "Neem water mee"),
    "Large sandy beach": T("Playa de arena grande", "Platja de sorra gran",
                           "Grande plage de sable", "Groot zandstrand"),
    "Long sandy beach": T("Playa de arena larga", "Platja de sorra llarga",
                          "Longue plage de sable", "Lang zandstrand"),
    "Big sandy bay": T("Gran bahía de arena", "Gran badia de sorra",
                       "Grande baie de sable", "Grote zandbaai"),
    "Promenade": T("Paseo marítimo", "Passeig marítim",
                   "Promenade", "Boulevard"),
    "Watersports": T("Deportes acuáticos", "Esports aquàtics",
                     "Sports nautiques", "Watersport"),
    "Marina": T("Puerto deportivo", "Port esportiu",
                "Port de plaisance", "Jachthaven"),
    "Good for families": T("Bien para familias", "Bé per a famílies",
                           "Bien pour les familles", "Goed voor gezinnen"),
    "Sunset views": T("Vistas al atardecer", "Vistes a la posta de sol",
                      "Vues au coucher du soleil", "Uitzicht bij zonsondergang"),
    "Several coves": T("Varias calas", "Diverses cales",
                       "Plusieurs criques", "Meerdere baaien"),
    "Very picturesque": T("Muy pintoresca", "Molt pintoresca",
                          "Très pittoresque", "Zeer schilderachtig"),
    "Havaneres festival": T("Festival de habaneras", "Cantada d'havaneres",
                            "Festival de havaneres", "Havaneres-festival"),
    "Cap Roig gardens": T("Jardines de Cap Roig", "Jardins de Cap Roig",
                          "Jardins de Cap Roig", "Tuinen van Cap Roig"),
    "Cap Roig gardens café": T("Cafetería de los jardines de Cap Roig",
                               "Cafeteria dels jardins de Cap Roig",
                               "Café des jardins de Cap Roig",
                               "Café van de tuinen van Cap Roig"),
    "Near Cap Roig gardens": T("Cerca de los jardines de Cap Roig",
                               "A prop dels jardins de Cap Roig",
                               "Près des jardins de Cap Roig",
                               "Bij de tuinen van Cap Roig"),
    "Afternoon shade": T("Sombra por la tarde", "Ombra a la tarda",
                         "Ombre l'après-midi", "Schaduw in de middag"),
    "Good facilities": T("Buenos servicios", "Bons serveis",
                         "Bons équipements", "Goede voorzieningen"),
    "Sunbed hire": T("Alquiler de hamacas", "Lloguer de gandules",
                     "Location de transats", "Ligbedverhuur"),
    "Sunbeds &amp; pedalos": T("Hamacas y patines", "Gandules i patins",
                               "Transats &amp; pédalos", "Ligbedden &amp; waterfietsen"),
    "Beach chiringuitos": T("Chiringuitos", "Xiringuitos",
                            "Paillotes de plage", "Strandtentjes"),
    "Pebble beach": T("Playa de cantos", "Platja de còdols",
                      "Plage de galets", "Kiezelstrand"),
    "Deep clear water": T("Agua profunda y clara", "Aigua profunda i clara",
                          "Eau profonde et claire", "Diep helder water"),
    "Difficult parking": T("Aparcamiento difícil", "Aparcament difícil",
                           "Stationnement difficile", "Lastig parkeren"),
    "Limited parking": T("Aparcamiento limitado", "Aparcament limitat",
                         "Stationnement limité", "Beperkt parkeren"),
    "Space even in August": T("Espacio incluso en agosto", "Espai fins i tot a l'agost",
                              "De la place même en août", "Ruimte zelfs in augustus"),
    "Windsurf &amp; kitesurf": T("Windsurf y kitesurf", "Windsurf i kitesurf",
                                 "Planche à voile &amp; kitesurf", "Windsurfen &amp; kitesurfen"),
    "Dunes &amp; pines": T("Dunas y pinos", "Dunes i pins",
                           "Dunes &amp; pins", "Duinen &amp; dennen"),
    "Good parking": T("Buen aparcamiento", "Bon aparcament",
                      "Bon stationnement", "Goed parkeren"),
    "Near medieval Pals": T("Cerca de Pals medieval", "A prop de Pals medieval",
                            "Près de Pals médiéval", "Bij het middeleeuwse Pals"),
    "Iberian settlement": T("Poblado ibérico", "Poblat ibèric",
                            "Village ibère", "Iberische nederzetting"),
    "Iberian ruins": T("Ruinas ibéricas", "Ruïnes ibèriques",
                       "Ruines ibères", "Iberische ruïnes"),
    "Undeveloped": T("Sin urbanizar", "Sense urbanitzar",
                     "Non bâtie", "Onbebouwd"),
    "Protected area": T("Espacio protegido", "Espai protegit",
                        "Espace protégé", "Beschermd gebied"),
    "Car park &amp; toilets": T("Aparcamiento y aseos", "Aparcament i lavabos",
                                "Parking &amp; toilettes", "Parkeerplaats &amp; toiletten"),
    "Very shallow water": T("Agua muy poco profunda", "Aigua molt poc profunda",
                            "Eau très peu profonde", "Zeer ondiep water"),
    "Ideal for small children": T("Ideal para niños pequeños", "Ideal per a nens petits",
                                  "Idéal pour les jeunes enfants", "Ideaal voor kleine kinderen"),
    "Easy parking": T("Aparcamiento fácil", "Aparcament fàcil",
                      "Stationnement facile", "Makkelijk parkeren"),
    "Castle ruins": T("Ruinas del castillo", "Ruïnes del castell",
                      "Ruines du château", "Kasteelruïne"),
    "Small coves": T("Calas pequeñas", "Cales petites",
                     "Petites criques", "Kleine baaien"),
    "Small children": T("Niños pequeños", "Nens petits",
                        "Jeunes enfants", "Kleine kinderen"),

    # ── parking values ───────────────────────────────────────────────────
    "Free": T("Gratuito", "Gratuït", "Gratuit", "Gratis"),
    "Paid": T("De pago", "De pagament", "Payant", "Betaald"),
    "Free &amp; paid": T("Gratuito y de pago", "Gratuït i de pagament",
                         "Gratuit &amp; payant", "Gratis &amp; betaald"),
    "Mixed — free further up the hill": T(
        "Mixto — gratuito subiendo la cuesta", "Mixt — gratuït pujant el turó",
        "Mixte — gratuit en montant", "Gemengd — gratis verderop de heuvel op"),
    "No parking": T("Sin aparcamiento", "Sense aparcament",
                    "Pas de stationnement", "Geen parkeergelegenheid"),
    "No road access": T("Sin acceso rodado", "Sense accés rodat",
                        "Pas d'accès routier", "Geen toegang met de auto"),
    "No access": T("Sin acceso", "Sense accés", "Pas d'accès", "Geen toegang"),
    "None — walk in": T("Ninguno — se llega a pie", "Cap — s'hi arriba a peu",
                        "Aucun — accès à pied", "Geen — te voet"),
    "Free street parking": T("Aparcamiento libre en la calle", "Aparcament lliure al carrer",
                             "Stationnement gratuit dans la rue", "Gratis parkeren op straat"),
    "Free street": T("Calle gratuita", "Carrer gratuït",
                     "Rue gratuite", "Gratis op straat"),
    "Free parking on": T("Aparcamiento gratuito en", "Aparcament gratuït a",
                         "Stationnement gratuit sur", "Gratis parkeren aan"),
    "Free car parks": T("Aparcamientos gratuitos", "Aparcaments gratuïts",
                        "Parkings gratuits", "Gratis parkeerplaatsen"),
    "Free car parks a short walk back": T(
        "Aparcamientos gratuitos a poca distancia",
        "Aparcaments gratuïts a poca distància",
        "Parkings gratuits à quelques minutes",
        "Gratis parkeerplaatsen op korte loopafstand"),
    "Free car park 200 m from the sand": T(
        "Aparcamiento gratuito a 200 m de la arena",
        "Aparcament gratuït a 200 m de la sorra",
        "Parking gratuit à 200 m du sable",
        "Gratis parkeerplaats op 200 m van het zand"),
    "Free parking near the beach": T(
        "Aparcamiento gratuito cerca de la playa", "Aparcament gratuït a prop de la platja",
        "Stationnement gratuit près de la plage", "Gratis parkeren bij het strand"),
    "Free street parking above the cove": T(
        "Aparcamiento libre en la calle sobre la cala",
        "Aparcament lliure al carrer sobre la cala",
        "Stationnement gratuit dans la rue au-dessus de la crique",
        "Gratis parkeren op straat boven de baai"),
    "Free the further up you go": T(
        "Gratuito cuanto más suba", "Gratuït com més amunt aneu",
        "Gratuit en montant", "Gratis naarmate u hoger komt"),
    "Free up the hill": T("Gratuito cuesta arriba", "Gratuït pujant",
                          "Gratuit en haut", "Gratis de heuvel op"),
    "Free further up": T("Gratuito más arriba", "Gratuït més amunt",
                         "Gratuit plus haut", "Gratis verderop"),
    "Free, 200 m": T("Gratuito, 200 m", "Gratuït, 200 m",
                     "Gratuit, 200 m", "Gratis, 200 m"),
    "Free off-season, €5 summer": T(
        "Gratuito fuera de temporada, 5 € en verano",
        "Gratuït fora de temporada, 5 € a l'estiu",
        "Gratuit hors saison, 5 € en été",
        "Gratis buiten het seizoen, €5 in de zomer"),
    "Free out of season, €5 a day in summer": T(
        "Gratuito fuera de temporada, 5 € al día en verano",
        "Gratuït fora de temporada, 5 € al dia a l'estiu",
        "Gratuit hors saison, 5 € par jour en été",
        "Gratis buiten het seizoen, €5 per dag in de zomer"),
    "Small paid car park at the cove": T(
        "Pequeño aparcamiento de pago en la cala",
        "Petit aparcament de pagament a la cala",
        "Petit parking payant à la crique",
        "Kleine betaalde parkeerplaats bij de baai"),
    "Paid car park at the cove": T(
        "Aparcamiento de pago en la cala", "Aparcament de pagament a la cala",
        "Parking payant à la crique", "Betaalde parkeerplaats bij de baai"),
    "Paid at cove": T("De pago en la cala", "De pagament a la cala",
                      "Payant à la crique", "Betaald bij de baai"),
    "Very limited paid parking": T(
        "Aparcamiento de pago muy limitado", "Aparcament de pagament molt limitat",
        "Stationnement payant très limité", "Zeer beperkt betaald parkeren"),
    "Paid, very limited": T("De pago, muy limitado", "De pagament, molt limitat",
                            "Payant, très limité", "Betaald, zeer beperkt"),
    "Nothing at the cove": T("Nada en la cala", "Res a la cala",
                             "Rien à la crique", "Niets bij de baai"),
    "Nothing on the beach": T("Nada en la playa", "Res a la platja",
                              "Rien sur la plage", "Niets op het strand"),
    "— take a picnic.": T("— lleve un picnic.", "— porteu-hi un pícnic.",
                          "— prévoyez un pique-nique.", "— neem een picknick mee."),
    "A small summer chiringuito": T(
        "Un pequeño chiringuito de verano", "Un petit xiringuito d'estiu",
        "Une petite paillote en été", "Een klein strandtentje in de zomer"),
    "two free public car parks at": T(
        "dos aparcamientos públicos gratuitos en", "dos aparcaments públics gratuïts a",
        "deux parkings publics gratuits à", "twee gratis openbare parkeerplaatsen aan"),
    "and": T("y", "i", "et", "en"),

    # ── "best for" column ────────────────────────────────────────────────
    "Everything — it's home": T("Todo — es nuestra playa", "Tot — és la nostra platja",
                                "Tout — c'est chez nous", "Alles — het is thuis"),
    "An early quiet swim": T("Un baño tranquilo temprano", "Un bany tranquil ben d'hora",
                             "Une baignade tranquille tôt le matin", "Een vroege rustige duik"),
    "Families, watersports, dining": T(
        "Familias, deportes acuáticos, comer",
        "Famílies, esports aquàtics, menjar",
        "Familles, sports nautiques, restauration",
        "Gezinnen, watersport, uit eten"),
    "Scenery, lunch, photos": T("Paisaje, comida, fotos", "Paisatge, dinar, fotos",
                                "Paysage, déjeuner, photos", "Landschap, lunch, foto's"),
    "Quiet swimming, shade": T("Baño tranquilo, sombra", "Bany tranquil, ombra",
                               "Baignade tranquille, ombre", "Rustig zwemmen, schaduw"),
    "A full family day out": T("Un día completo en familia", "Un dia complet en família",
                               "Une journée en famille", "Een hele dag met het gezin"),
    "Charm, deep clear water": T("Encanto, agua profunda y clara",
                                 "Encant, aigua profunda i clara",
                                 "Charme, eau profonde et claire",
                                 "Charme, diep helder water"),
    "Space, nature, ruins": T("Espacio, naturaleza, ruinas", "Espai, natura, ruïnes",
                              "Espace, nature, ruines", "Ruimte, natuur, ruïnes"),
    "Long walks, windsurfing": T("Paseos largos, windsurf", "Passejades llargues, windsurf",
                                 "Longues marches, planche à voile", "Lange wandelingen, windsurfen"),
    "Sand": T("Arena", "Sorra", "Sable", "Zand"),
    "Shingle": T("Grava", "Grava", "Gravier", "Grind"),
    "Pebble": T("Cantos", "Còdols", "Galets", "Kiezels"),
    "Coarse sand": T("Arena gruesa", "Sorra gruixuda", "Sable grossier", "Grof zand"),
    "Sand &amp; shingle": T("Arena y grava", "Sorra i grava",
                            "Sable et gravier", "Zand en grind"),
    "Pebble &amp; rock": T("Cantos y roca", "Còdols i roca",
                           "Galets et rochers", "Kiezels en rots"),

    # ── misc ─────────────────────────────────────────────────────────────
    "10 min walk": T("10 min a pie", "10 min a peu", "10 min à pied", "10 min lopen"),
    "2 km on foot": T("2 km a pie", "2 km a peu", "2 km à pied", "2 km te voet"),
    "~2 km on foot": T("~2 km a pie", "~2 km a peu", "~2 km à pied", "~2 km te voet"),
    "45–50 min each way": T("45–50 min por trayecto", "45–50 min per trajecte",
                            "45–50 min par trajet", "45–50 min enkele reis"),
    "not possible": T("no es posible", "no és possible",
                      "impossible", "niet mogelijk"),
    "Tamariu (5 min drive)": T("Tamariu (5 min en coche)", "Tamariu (5 min en cotxe)",
                               "Tamariu (5 min en voiture)", "Tamariu (5 min rijden)"),
    "Toc al Mar, Aiguablava (5 min)": T(
        "Toc al Mar, Aiguablava (5 min)", "Toc al Mar, Aiguablava (5 min)",
        "Toc al Mar, Aiguablava (5 min)", "Toc al Mar, Aiguablava (5 min)"),
    "Calella de Palafrugell (20 min walk)": T(
        "Calella de Palafrugell (20 min a pie)", "Calella de Palafrugell (20 min a peu)",
        "Calella de Palafrugell (20 min à pied)", "Calella de Palafrugell (20 min lopen)"),
    "Up in Begur town (10 min)": T(
        "En el pueblo de Begur (10 min)", "Al poble de Begur (10 min)",
        "Dans le village de Begur (10 min)", "In het stadje Begur (10 min)"),
    "In Pals village (5 min inland)": T(
        "En el pueblo de Pals (5 min tierra adentro)",
        "Al poble de Pals (5 min cap a l'interior)",
        "Au village de Pals (5 min dans les terres)",
        "In het dorp Pals (5 min landinwaarts)"),
    "Palamós (10 min)": T("Palamós (10 min)", "Palamós (10 min)",
                          "Palamós (10 min)", "Palamós (10 min)"),
    "Palamós old town (5 min)": T(
        "Casco antiguo de Palamós (5 min)", "Nucli antic de Palamós (5 min)",
        "Vieille ville de Palamós (5 min)", "Oude stad van Palamós (5 min)"),
    "Terrace bars on the passeig": T(
        "Bares con terraza en el passeig", "Bars amb terrassa al passeig",
        "Bars en terrasse sur le passeig", "Terrasbars aan de passeig"),
    "→ See our walking routes page": T(
        "→ Ver nuestra página de rutas a pie", "→ Vegeu la nostra pàgina de rutes a peu",
        "→ Voir notre page des randonnées", "→ Bekijk onze wandelroutepagina"),
    "→ Our full Tamariu restaurant guide": T(
        "→ Nuestra guía completa de restaurantes de Tamariu",
        "→ La nostra guia completa de restaurants de Tamariu",
        "→ Notre guide complet des restaurants de Tamariu",
        "→ Onze volledige restaurantgids voor Tamariu"),
    "📍 View on Google Maps": T(
        "📍 Ver en Google Maps", "📍 Veure a Google Maps",
        "📍 Voir sur Google Maps", "📍 Bekijk op Google Maps"),
    "blue zone": T("zona azul", "zona blava", "zone bleue", "blauwe zone"),
    "camí de ronda": T("camí de ronda", "camí de ronda",
                       "camí de ronda", "camí de ronda"),
}
