# -*- coding: utf-8 -*-
"""Generated German glossary for the 13 standalone pages. See build_de_standalone.py."""

STRINGS_DE_STANDALONE = {
    'Tamariu Chalet — Costa Brava Accommodation': 'Tamariu Chalet — Costa Brava Unterkunft',
    'Tamariu': 'Tamariu',
    'Chalet': 'Chalet',
    'Restaurants &amp; Bars': 'Restaurants &amp; Bars',
    'EN': 'EN',
    'ES': 'ES',
    'CA': 'CA',
    'FR': 'FR',
    'NL': 'NL',
    'Costa Brava · Catalunya · Spain': 'Costa Brava · Catalunya · Spanien',
    'Welcome to': 'Willkommen im',
    'Tamariu Chalet': 'Tamariu Chalet',
    'Three rooms &amp; a private studio apartment, steps from the sea': 'Drei Zimmer &amp; ein privates Studio-Apartment, wenige Schritte vom Meer',
    'Book direct and save 10% on online platform prices.': 'Buchen Sie direkt und sparen Sie 10 % gegenüber den Preisen der Online-Plattformen.',
    'Scroll': 'Scrollen',
    'Our Home, Your Holiday': 'Unser Zuhause, Ihr Urlaub',
    'Life on the Costa Brava': 'Das Leben an der Costa Brava',
    "Tamariu is one of the Costa Brava's best-kept secrets — a small, unhurried fishing village\n      nestled in a sheltered cove where pine trees meet clear turquoise water. Unlike its livelier\n      neighbours, Tamariu has resisted mass tourism, preserving the charm of whitewashed houses,\n      small fishing boats and the gentle rhythm of Mediterranean life.": 'Tamariu ist eines der bestgehüteten Geheimnisse der Costa Brava — ein kleines, gemächliches Fischerdorf, eingebettet in eine geschützte Bucht, wo Pinien auf klares türkisfarbenes Wasser treffen. Anders als seine lebhafteren Nachbarn hat sich Tamariu dem Massentourismus widersetzt und den Charme weiß getünchter Häuser, kleiner Fischerboote und des sanften Rhythmus mediterranen Lebens bewahrt.',
    'The village sits within the municipality of Palafrugell, in the heart of the Costa Brava —\n      literally the "Wild Coast" — a stretch of rugged Catalan coastline that unfolds between the\n      Pyrenees and Barcelona. Here, dramatic limestone cliffs plunge into the sea, carving out\n      hidden coves and crystalline inlets accessible only by boat or narrow footpath.': 'Das Dorf liegt in der Gemeinde Palafrugell, im Herzen der Costa Brava — wörtlich der „Wilden Küste" — einem Abschnitt der rauen katalanischen Küste, der sich zwischen den Pyrenäen und Barcelona erstreckt. Hier stürzen dramatische Kalksteinklippen ins Meer und formen versteckte Buchten und kristallklare Meeresarme, die nur mit dem Boot oder über schmale Pfade erreichbar sind.',
    'Beyond the beach, the surrounding hinterland rewards exploration. Medieval hilltop towns\n      such as Pals, Peratallada and Begur rise from golden plains dotted with vineyards and\n      olive groves. The city of Girona — with its Roman walls, cathedral and famous Jewish Quarter —\n      is just 40 minutes by car, making a superb day trip.': 'Über den Strand hinaus belohnt das umliegende Hinterland die Erkundung. Mittelalterliche Hügelstädte wie Pals, Peratallada und Begur erheben sich aus goldenen Ebenen, gesprenkelt mit Weinbergen und Olivenhainen. Die Stadt Girona — mit ihren römischen Mauern, der Kathedrale und dem berühmten Jüdischen Viertel — ist nur 40 Autominuten entfernt und ein hervorragender Tagesausflug.',
    "The area is a cyclist's paradise: rolling country roads, the famous L'Étape du Tour route\n      and gentle coastal paths attract riders from across Europe each spring and summer. Walkers\n      are equally rewarded by the GR-92 coastal path, which threads through Tamariu and connects\n      a string of perfect beaches. The sea itself offers snorkelling over Posidonia meadows,\n      diving at pristine rocky reefs, kayaking, paddleboarding and boat hire.": "Die Gegend ist ein Paradies für Radfahrer: sanft hügelige Landstraßen, die berühmte Route L'Étape du Tour und sanfte Küstenwege ziehen jedes Frühjahr und jeden Sommer Fahrer aus ganz Europa an. Wanderer werden vom Küstenpfad GR-92 ebenso belohnt, der sich durch Tamariu zieht und eine Reihe perfekter Strände verbindet. Das Meer selbst bietet Schnorcheln über Posidonia-Wiesen, Tauchen an unberührten Felsriffen, Kajakfahren, Paddleboarding und Bootsverleih.",
    'Tamariu Chalet is a lovingly maintained property offering three comfortable en-suite rooms\n      in the main house and a fully self-contained private studio apartment — all sharing access to a\n      tranquil pool, a shaded garden and a patio perfect for long Mediterranean evenings.': 'Das Tamariu Chalet ist ein liebevoll gepflegtes Anwesen mit drei komfortablen Zimmern mit eigenem Bad im Haupthaus und einem voll ausgestatteten, unabhängigen privaten Studio-Apartment — alle mit Zugang zu einem ruhigen Pool, einem schattigen Garten und einer Terrasse, ideal für lange mediterrane Abende.',
    'Explore Rooms →': 'Zimmer entdecken →',
    'The Chalet &amp; Gardens': 'Das Chalet &amp; die Gärten',
    'Your home on the Costa Brava': 'Ihr Zuhause an der Costa Brava',
    'Pool &amp; Garden': 'Pool &amp; Garten',
    'Pool View': 'Poolblick',
    'Pool — Second View': 'Pool — Zweite Ansicht',
    'Patio &amp; Eating Area': 'Terrasse &amp; Essbereich',
    'Courtyard': 'Innenhof',
    'Courtyard — Second View': 'Innenhof — Zweite Ansicht',
    'Outdoor Dining': 'Essen im Freien',
    'BBQ &amp; Outdoor Dining': 'Grill &amp; Essen im Freien',
    'Indoor Dining': 'Essen drinnen',
    'Street View': 'Straßenansicht',
    "Where You'll Stay": 'Wo Sie wohnen',
    'Our Rooms &amp; Apartment': 'Unsere Zimmer &amp; Apartment',
    "A generous double bedroom with garden views, sharing the house's well-equipped bathroom facilities.": 'Ein großzügiges Doppelzimmer mit Gartenblick, das die gut ausgestatteten Badeinrichtungen des Hauses mitbenutzt.',
    'From': 'Ab',
    'View Room': 'Zimmer ansehen',
    'Two single beds, light-filled and airy — ideal for friends or siblings exploring the coast.': 'Zwei Einzelbetten, lichtdurchflutet und luftig — ideal für Freunde oder Geschwister, die die Küste erkunden.',
    'A second twin room with a warm, relaxed feel — sharing the same comfortable house amenities.': 'Ein zweites Zweibettzimmer mit warmer, entspannter Atmosphäre — mit denselben komfortablen Annehmlichkeiten des Hauses.',
    'A fully self-contained studio apartment with private entrance, overlooking the pool and garden.': 'Ein voll ausgestattetes Studio-Apartment mit privatem Eingang, mit Blick auf Pool und Garten.',
    'View Apartment': 'Apartment ansehen',
    'Life on the Coast': 'Das Leben an der Küste',
    'Tamariu Beach &amp; Village': 'Strand &amp; Dorf Tamariu',
    'Tamariu Beach': 'Strand von Tamariu',
    'Beach Horizon': 'Strandhorizont',
    'Diving Board': 'Sprungbrett',
    'Evening Sunset': 'Abendlicher Sonnenuntergang',
    'GR-92 Coastal Path': 'Küstenpfad GR-92',
    'Tamariu Village': 'Dorf Tamariu',
    'Tamariu — Aerial View': 'Tamariu — Luftaufnahme',
    'Tamariu Cove': 'Bucht von Tamariu',
    'Beach Life': 'Strandleben',
    'Tamariu Shore': 'Küste von Tamariu',
    'Tamariu Seafront': 'Strandpromenade von Tamariu',
    'Tamariu Location': 'Lage von Tamariu',
    'Medieval city, 40 min away': 'Mittelalterliche Stadt, 40 Min. entfernt',
    'Routes, hire &amp; gran fondos': 'Routen, Verleih &amp; Gran Fondos',
    'Diving, kayaking, paddleboard': 'Tauchen, Kajakfahren, Paddleboard',
    'Weekly artisan &amp; food markets': 'Wöchentliche Kunsthandwerks- &amp; Lebensmittelmärkte',
    'Map, directions &amp; bus routes': 'Karte, Wegbeschreibung &amp; Buslinien',
    'Check availability &amp; enquire': 'Verfügbarkeit prüfen &amp; anfragen',
    'A peaceful retreat on the Costa Brava — where the pine forests meet the sea in the unspoiled village of Tamariu, Catalunya.': 'Ein friedlicher Rückzugsort an der Costa Brava — wo die Pinienwälder im unberührten Dorf Tamariu, Katalonien, auf das Meer treffen.',
    '📍 Tamariu, Palafrugell, Girona, Catalunya': '📍 Tamariu, Palafrugell, Girona, Katalonien',
    'Markets': 'Märkte',
    'Restaurants': 'Restaurants',
    'Travel Info': 'Reiseinfos',
    'Palafrugell Tourist Info': 'Touristeninfo Palafrugell',
    '&copy; 2025 Tamariu Chalet · tamariuchalet@gmail.com': '&copy; 2025 Tamariu Chalet · tamariuchalet@gmail.com',
    'Tamariu, Costa Brava, Catalunya, Spain': 'Tamariu, Costa Brava, Katalonien, Spanien',
    'Tamariu cove, Costa Brava': 'Bucht von Tamariu, Costa Brava',
    'Pool and garden': 'Pool und Garten',
    'Pool view': 'Poolblick',
    'Pool second view': 'Pool zweite Ansicht',
    'Patio and eating area': 'Terrasse und Essbereich',
    'Courtyard second view': 'Innenhof zweite Ansicht',
    'Outdoor dining': 'Essen im Freien',
    'BBQ and outdoor dining': 'Grill und Essen im Freien',
    'Indoor dining': 'Essen drinnen',
    'Street view': 'Straßenansicht',
    'Evening Sunset on the Beach': 'Abendlicher Sonnenuntergang am Strand',
    'View from GR-92 coastal path': 'Blick vom Küstenpfad GR-92',
    'Double Room — Tamariu Chalet': 'Doppelzimmer — Tamariu Chalet',
    'Accommodation → Double Room': 'Unterkunft → Doppelzimmer',
    'About This Room': 'Über dieses Zimmer',
    'A comfortable, well-appointed double room with a relaxed Mediterranean character.\n        Natural light fills the space throughout the day, and the garden outlook lends a sense of\n        calm privacy. The room benefits from quality bed linen, ample storage and convenient\n        access to the shared bathroom facilities just across the hall. Free on-street parking is available just outside, and secure bike storage is provided at the chalet.': 'Ein komfortables, gut ausgestattetes Doppelzimmer mit entspanntem mediterranem Charakter. Natürliches Licht erfüllt den Raum den ganzen Tag über, und der Blick in den Garten vermittelt ein Gefühl ruhiger Privatsphäre. Das Zimmer verfügt über hochwertige Bettwäsche, reichlich Stauraum und bequemen Zugang zu den Gemeinschaftsbädern gleich gegenüber auf dem Flur. Kostenloses Parken am Straßenrand ist direkt vor der Tür verfügbar, und im Chalet steht ein sicherer Fahrradabstellplatz bereit.',
    '🌿 Patio &amp; Eating Area': '🌿 Terrasse &amp; Essbereich',
    '🏊 Pool &amp; Garden': '🏊 Pool &amp; Garten',
    '🚿 Bathrooms &amp; Kitchen': '🚿 Bäder &amp; Küche',
    'Facilities': 'Ausstattung',
    '🛏 Room Facilities': '🛏 Zimmerausstattung',
    'USB charging points': 'USB-Ladeanschlüsse',
    'Mosquito screens': 'Moskitonetze',
    'Ceiling fan': 'Deckenventilator',
    'Spacious storage with hangers': 'Geräumiger Stauraum mit Kleiderbügeln',
    'Room darkening blinds': 'Verdunkelungsrollos',
    'Safe': 'Safe',
    '🚿 Bathroom': '🚿 Badezimmer',
    'Shower': 'Dusche',
    'Bath': 'Badewanne',
    'Toilet': 'Toilette',
    'Handwash basin': 'Waschbecken',
    'Hairdryer': 'Haartrockner',
    'Bath soap &amp; shampoo': 'Duschseife &amp; Shampoo',
    '🍳 Kitchen': '🍳 Küche',
    'Coffee making facilities': 'Kaffeezubereitung',
    'Kettle': 'Wasserkocher',
    'Toaster': 'Toaster',
    'Microwave oven': 'Mikrowelle',
    'Stove / hob': 'Herd / Kochfeld',
    'Crockery &amp; cutlery': 'Geschirr &amp; Besteck',
    'Glasses': 'Gläser',
    'Pots &amp; pans': 'Töpfe &amp; Pfannen',
    'Smoke alarm': 'Rauchmelder',
    '🌿 Outdoor Facilities': '🌿 Außenausstattung',
    'BBQ': 'Grill',
    'Covered outdoor dining area': 'Überdachter Essbereich im Freien',
    'Seated pergola area': 'Pergola mit Sitzgelegenheiten',
    'Petanque court': 'Boule-Platz',
    '8 × 4 m pool': 'Pool 8 × 4 m',
    'Decking area': 'Holzterrasse',
    'Sun loungers': 'Sonnenliegen',
    'Free on-street parking': 'Kostenloses Parken am Straßenrand',
    'Secure bike storage': 'Sicherer Fahrradabstellplatz',
    'Clothes drying area': 'Wäschetrockenbereich',
    '🏠 General': '🏠 Allgemein',
    'Ironing facilities': 'Bügelmöglichkeit',
    'Luggage drop off': 'Gepäckabgabe',
    'Dedicated fridge storage space': 'Eigener Kühlschrankbereich',
    'Fire extinguisher': 'Feuerlöscher',
    'First aid kit': 'Erste-Hilfe-Kasten',
    'Washing machine (at cost)': 'Waschmaschine (gegen Gebühr)',
    'Rates — Double Room': 'Preise — Doppelzimmer',
    'Season': 'Saison',
    'Dates': 'Zeitraum',
    'Rate': 'Preis',
    'Min Stay': 'Mindestaufenthalt',
    'Early': 'Vorsaison',
    '01 Jan – 30 Apr': '01 Jan – 30 Apr',
    'Closed': 'Geschlossen',
    'Spring': 'Frühling',
    '01 May – 31 May': '01 Mai – 31 Mai',
    '2 nights': '2 Nächte',
    'Summer': 'Sommer',
    '01 Jun – 31 Aug': '01 Jun – 31 Aug',
    '3 nights': '3 Nächte',
    'Late': 'Nachsaison',
    '01 Sep – 31 Dec': '01 Sep – 31 Dez',
    'Rates are per room per night.': 'Preise gelten pro Zimmer pro Nacht.',
    'A one-off cleaning fee of €30 applies per stay.': 'Eine einmalige Reinigungsgebühr von 30 € fällt pro Aufenthalt an.',
    '📅 Check Availability': '📅 Verfügbarkeit prüfen',
    'What Our Guests Say': 'Was unsere Gäste sagen',
    '5.0 ★ average · 24 reviews': '5,0 ★ Durchschnitt · 24 Bewertungen',
    'Read all 24 reviews &rarr;': 'Alle 24 Bewertungen lesen &rarr;',
    'Double Room — view 2': 'Doppelzimmer — Ansicht 2',
    'Double Room — view 3': 'Doppelzimmer — Ansicht 3',
    'Previous review': 'Vorherige Bewertung',
    'Next review': 'Nächste Bewertung',
    'Review 1': 'Bewertung 1',
    'Review 2': 'Bewertung 2',
    'Review 3': 'Bewertung 3',
    'Review 4': 'Bewertung 4',
    'Review 5': 'Bewertung 5',
    'Review 6': 'Bewertung 6',
    'Review 7': 'Bewertung 7',
    'Review 8': 'Bewertung 8',
    'Review 9': 'Bewertung 9',
    'Review 10': 'Bewertung 10',
    'Review 11': 'Bewertung 11',
    'Review 12': 'Bewertung 12',
    'Review 13': 'Bewertung 13',
    'Review 14': 'Bewertung 14',
    'Review 15': 'Bewertung 15',
    'Review 16': 'Bewertung 16',
    'Review 17': 'Bewertung 17',
    'Review 18': 'Bewertung 18',
    'Review 19': 'Bewertung 19',
    'Review 20': 'Bewertung 20',
    'Review 21': 'Bewertung 21',
    'Review 22': 'Bewertung 22',
    'Review 23': 'Bewertung 23',
    'Review 24': 'Bewertung 24',
    'Double/Twin Room 1 — Tamariu Chalet': 'Doppel-/Zweibettzimmer 1 — Tamariu Chalet',
    'Accommodation → Double/Twin Room 1': 'Unterkunft → Doppel-/Zweibettzimmer 1',
    'A bright and cheerful room with a relaxed Mediterranean character, which can be configured\n        as either a double bed or two separate single beds — just let us know your preference when\n        you enquire. Natural light fills the space throughout the day, and the garden outlook lends\n        a sense of calm privacy. The room benefits from quality bed linen, ample storage and\n        convenient access to the shared bathroom facilities just across the hall. Free on-street parking is available just outside, and secure bike storage is provided at the chalet.': 'Ein helles und freundliches Zimmer mit entspanntem mediterranem Charakter, das entweder als Doppelbett oder als zwei getrennte Einzelbetten hergerichtet werden kann — teilen Sie uns bei Ihrer Anfrage einfach Ihre Präferenz mit. Natürliches Licht erfüllt den Raum den ganzen Tag über, und der Blick in den Garten vermittelt ein Gefühl ruhiger Privatsphäre. Das Zimmer verfügt über hochwertige Bettwäsche, reichlich Stauraum und bequemen Zugang zu den Gemeinschaftsbädern gleich gegenüber auf dem Flur. Kostenloses Parken am Straßenrand ist direkt vor der Tür verfügbar, und im Chalet steht ein sicherer Fahrradabstellplatz bereit.',
    'Rates — Double/Twin Room 1': 'Preise — Doppel-/Zweibettzimmer 1',
    '4.8 ★ average · 30 reviews': '4,8 ★ Durchschnitt · 30 Bewertungen',
    'Read all 30 reviews &rarr;': 'Alle 30 Bewertungen lesen &rarr;',
    'Double/Twin Room 1 — view 2': 'Doppel-/Zweibettzimmer 1 — Ansicht 2',
    'Double/Twin Room 1 — view 3': 'Doppel-/Zweibettzimmer 1 — Ansicht 3',
    'Review 25': 'Bewertung 25',
    'Review 26': 'Bewertung 26',
    'Review 27': 'Bewertung 27',
    'Review 28': 'Bewertung 28',
    'Review 29': 'Bewertung 29',
    'Review 30': 'Bewertung 30',
    'Double/Twin Room 2 — Tamariu Chalet': 'Doppel-/Zweibettzimmer 2 — Tamariu Chalet',
    'Accommodation → Double/Twin Room 2': 'Unterkunft → Doppel-/Zweibettzimmer 2',
    'A relaxed, comfortable room with a warm Mediterranean feel, which can be configured\n        as either a double bed or two separate single beds — just let us know your preference when\n        you enquire. Natural light fills the space throughout the day, and the garden outlook lends\n        a sense of calm privacy. The room benefits from quality bed linen, ample storage and\n        convenient access to the shared bathroom facilities just across the hall. Free on-street parking is available just outside, and secure bike storage is provided at the chalet.': 'Ein entspanntes, komfortables Zimmer mit warmer mediterraner Atmosphäre, das entweder als Doppelbett oder als zwei getrennte Einzelbetten hergerichtet werden kann — teilen Sie uns bei Ihrer Anfrage einfach Ihre Präferenz mit. Natürliches Licht erfüllt den Raum den ganzen Tag über, und der Blick in den Garten vermittelt ein Gefühl ruhiger Privatsphäre. Das Zimmer verfügt über hochwertige Bettwäsche, reichlich Stauraum und bequemen Zugang zu den Gemeinschaftsbädern gleich gegenüber auf dem Flur. Kostenloses Parken am Straßenrand ist direkt vor der Tür verfügbar, und im Chalet steht ein sicherer Fahrradabstellplatz bereit.',
    'Rates — Double/Twin Room 2': 'Preise — Doppel-/Zweibettzimmer 2',
    '4.9 ★ average · 23 reviews': '4,9 ★ Durchschnitt · 23 Bewertungen',
    'Read all 23 reviews &rarr;': 'Alle 23 Bewertungen lesen &rarr;',
    'Double/Twin Room 2 — view 2': 'Doppel-/Zweibettzimmer 2 — Ansicht 2',
    'Studio Apartment — Tamariu Chalet': 'Studio-Apartment — Tamariu Chalet',
    'Accommodation → Studio Apartment': 'Unterkunft → Studio-Apartment',
    'About the Apartment': 'Über das Apartment',
    'Our fully self-contained Studio Apartment offers the ultimate in privacy and independence.\n        With its own private entrance, the apartment sits directly alongside the pool and garden,\n        making it perfect for couples or small families who want the freedom of a home from home\n        combined with the surroundings of Tamariu Chalet.': 'Unser voll ausgestattetes Studio-Apartment bietet ein Höchstmaß an Privatsphäre und Unabhängigkeit. Mit eigenem privatem Eingang liegt das Apartment direkt am Pool und Garten und ist damit perfekt für Paare oder kleine Familien, die die Freiheit eines Zuhauses fern von zu Hause in Kombination mit der Umgebung des Tamariu Chalet wünschen.',
    'The apartment features a comfortable bedroom, a well-equipped private kitchen, a sitting\n        area and its own bathroom — everything you need for a relaxed, independent stay on the\n        Costa Brava. Step outside onto your terrace to the sight and sound of the pool, with the\n        garden beyond. Free on-street parking is available just outside, and secure bike storage is provided at the chalet.': 'Das Apartment verfügt über ein komfortables Schlafzimmer, eine gut ausgestattete private Küche, einen Sitzbereich und ein eigenes Bad — alles, was Sie für einen entspannten, unabhängigen Aufenthalt an der Costa Brava brauchen. Treten Sie auf Ihre Terrasse hinaus, zum Anblick und Klang des Pools, mit dem Garten dahinter. Kostenloses Parken am Straßenrand ist direkt vor der Tür verfügbar, und im Chalet steht ein sicherer Fahrradabstellplatz bereit.',
    'Fans': 'Ventilatoren',
    'Cot available on request': 'Kinderbett auf Anfrage verfügbar',
    'Private en-suite bathroom': 'Eigenes Bad (en suite)',
    'Private kitchen': 'Private Küche',
    'Terrace': 'Terrasse',
    'Rates — Studio Apartment': 'Preise — Studio-Apartment',
    '4 nights': '4 Nächte',
    'Rates are per apartment per night.': 'Preise gelten pro Apartment pro Nacht.',
    'A one-off cleaning fee of €45 applies per stay.': 'Eine einmalige Reinigungsgebühr von 45 € fällt pro Aufenthalt an.',
    '5.0 ★ average · 26 reviews': '5,0 ★ Durchschnitt · 26 Bewertungen',
    'Read all 26 reviews &rarr;': 'Alle 26 Bewertungen lesen &rarr;',
    'Living area': 'Wohnbereich',
    'Kitchen': 'Küche',
    'Catalonian Cuisine — Tamariu Chalet': 'Katalanische Küche — Tamariu Chalet',
    'Tamariu Chalet Home': 'Tamariu Chalet Startseite',
    'Cuisine': 'Küche',
    'Language': 'Sprache',
    'Culture': 'Kultur',
    'History': 'Geschichte',
    'Cities': 'Städte',
    'Facts': 'Fakten',
    'The Heart of Catalan Cooking': 'Das Herz der katalanischen Küche',
    'Catalan cuisine is one of the oldest and most respected in Europe. It draws on the abundance of the Mediterranean coastline, the fertile inland plains, and the produce of the Pyrenean foothills. The result is a cuisine that is at once rustic and refined — built on simple, quality ingredients and bold, honest flavours.': 'Die katalanische Küche ist eine der ältesten und angesehensten Europas. Sie schöpft aus dem Reichtum der Mittelmeerküste, den fruchtbaren Ebenen des Landesinneren und den Erzeugnissen der Pyrenäenausläufer. Das Ergebnis ist eine Küche, die zugleich rustikal und raffiniert ist — aufgebaut auf einfachen, hochwertigen Zutaten und kräftigen, ehrlichen Aromen.',
    'The defining characteristic of Catalan food is the meeting of sea and mountain (': 'Das bestimmende Merkmal der katalanischen Küche ist das Zusammentreffen von Meer und Berg (',
    'mar i muntanya': 'mar i muntanya',
    '). Combinations that might seem unusual elsewhere — chicken with prawns, pork with mussels, rabbit with cuttlefish — are perfectly natural here and rooted in centuries of tradition.': '). Kombinationen, die anderswo ungewöhnlich erscheinen mögen — Hähnchen mit Gambas, Schwein mit Muscheln, Kaninchen mit Tintenfisch — sind hier vollkommen natürlich und in Jahrhunderten der Tradition verwurzelt.',
    'The golden rule of Catalan cooking:': 'Die goldene Regel der katalanischen Küche:',
    'start with the best possible ingredients and do as little as necessary to them. Quality olive oil, ripe tomatoes, fresh garlic, and good bread form the backbone of almost every meal.': 'Beginnen Sie mit den bestmöglichen Zutaten und tun Sie so wenig wie nötig mit ihnen. Hochwertiges Olivenöl, reife Tomaten, frischer Knoblauch und gutes Brot bilden das Rückgrat fast jeder Mahlzeit.',
    'Essential Dishes': 'Unverzichtbare Gerichte',
    'Pa amb Tomàquet': 'Pa amb Tomàquet',
    'The cornerstone of Catalan food. Bread rubbed with ripe tomato, drizzled with olive oil and finished with salt. Eaten at virtually every meal, it is simplicity perfected.': 'Der Grundpfeiler der katalanischen Küche. Brot, mit reifer Tomate eingerieben, mit Olivenöl beträufelt und mit Salz abgeschmeckt. Bei praktisch jeder Mahlzeit gegessen, ist es vollendete Einfachheit.',
    "Escudella i Carn d'Olla": "Escudella i Carn d'Olla",
    'A hearty winter stew made with chickpeas, vegetables, pork, chicken, and large meatballs called': 'Ein herzhafter Wintereintopf mit Kichererbsen, Gemüse, Schweinefleisch, Hähnchen und großen Fleischklößen namens',
    'pilota': 'pilota',
    '. Traditionally served in two courses — first the broth, then the meat.': '. Traditionell in zwei Gängen serviert — zuerst die Brühe, dann das Fleisch.',
    'Fideuà': 'Fideuà',
    'A cousin of paella, made with short noodles instead of rice, cooked in a rich fish and shellfish broth. Originated in Gandia but deeply embedded in Catalan coastal culture. Served with alioli.': 'Ein Verwandter der Paella, zubereitet mit kurzen Nudeln statt Reis, gekocht in einer reichhaltigen Fisch- und Meeresfrüchtebrühe. Ursprünglich aus Gandia, aber tief in der katalanischen Küstenkultur verwurzelt. Mit Alioli serviert.',
    'Crema Catalana': 'Crema Catalana',
    'The original burnt cream — a silky custard flavoured with lemon zest and cinnamon, topped with a layer of caramelised sugar. Dating back to the 14th century, it predates French crème brûlée.': 'Die ursprüngliche gebrannte Creme — eine seidige Creme, verfeinert mit Zitronenschale und Zimt, überzogen mit einer Schicht karamellisierten Zuckers. Sie stammt aus dem 14. Jahrhundert und ist älter als die französische Crème brûlée.',
    'Calçots amb Romesco': 'Calçots amb Romesco',
    'Long spring onions grilled over open flame until charred outside and sweet within. Eaten with romesco — a rich sauce of toasted almonds, hazelnuts, dried peppers, tomato and olive oil. A true seasonal celebration.': 'Lange Frühlingszwiebeln, über offener Flamme gegrillt, bis sie außen verkohlt und innen süß sind. Gegessen mit Romesco — einer reichhaltigen Sauce aus gerösteten Mandeln, Haselnüssen, getrockneten Paprika, Tomate und Olivenöl. Ein echtes saisonales Fest.',
    'Suquet de Peix': 'Suquet de Peix',
    "A fisherman's stew from the Costa Brava — fresh catch of the day simmered with potatoes, saffron, tomato and a": 'Ein Fischereintopf von der Costa Brava — der frische Fang des Tages, geköchelt mit Kartoffeln, Safran, Tomate und einer',
    'picada': 'picada',
    'of almonds, garlic, parsley and olive oil. Simple, deeply flavourful.': 'aus Mandeln, Knoblauch, Petersilie und Olivenöl. Einfach, tief aromatisch.',
    'Botifarra': 'Botifarra',
    'The great Catalan sausage, made with pork, salt and pepper. Grilled over charcoal and served with white beans (': 'Die große katalanische Wurst, hergestellt aus Schweinefleisch, Salz und Pfeffer. Über Holzkohle gegrillt und mit weißen Bohnen serviert (',
    'mongetes': 'mongetes',
    '). There are dozens of regional varieties including black, white and sweet versions.': '). Es gibt Dutzende regionaler Varianten, darunter schwarze, weiße und süße Versionen.',
    'Esqueixada': 'Esqueixada',
    'A refreshing salt cod salad with tomatoes, onion, olives, olive oil and vinegar. The fish is shredded raw rather than cooked —': 'Ein erfrischender Stockfischsalat mit Tomaten, Zwiebeln, Oliven, Olivenöl und Essig. Der Fisch wird roh zerpflückt statt gekocht —',
    'esqueixar': 'esqueixar',
    'means to shred or tear. A classic summer starter.': 'bedeutet zerpflücken oder zerreißen. Eine klassische sommerliche Vorspeise.',
    'Mel i Mató': 'Mel i Mató',
    'The simplest and most perfect of Catalan desserts — fresh white curd cheese drizzled with dark honey, often from local bees. Mató is made in the Pyrenean foothills and sold in local markets.': 'Das einfachste und perfekteste der katalanischen Desserts — frischer weißer Frischkäse, beträufelt mit dunklem Honig, oft von einheimischen Bienen. Mató wird in den Pyrenäenausläufern hergestellt und auf lokalen Märkten verkauft.',
    'Coca': 'Coca',
    'A flat pastry or bread base topped with a huge range of sweet or savoury ingredients — caramelised onion, peppers, pine nuts, candied fruits. Eaten at festivals and family gatherings throughout the year.': 'Ein flacher Teig- oder Brotboden, belegt mit einer großen Bandbreite süßer oder herzhafter Zutaten — karamellisierte Zwiebeln, Paprika, Pinienkerne, kandierte Früchte. Gegessen bei Festen und Familienzusammenkünften das ganze Jahr über.',
    'Key Sauces and Condiments': 'Wichtige Saucen und Gewürze',
    'Catalan cooking relies on a handful of fundamental sauces that appear throughout the cuisine.': 'Die katalanische Küche stützt sich auf eine Handvoll grundlegender Saucen, die in der gesamten Küche vorkommen.',
    'Alioli': 'Alioli',
    '— a thick emulsion of garlic and olive oil — accompanies fish, grilled meats and fideuà.': '— eine dicke Emulsion aus Knoblauch und Olivenöl — begleitet Fisch, gegrilltes Fleisch und Fideuà.',
    'Romesco': 'Romesco',
    'is a complex sauce of roasted tomatoes, dried peppers, toasted nuts and olive oil used with calçots, fish and vegetables.': 'ist eine komplexe Sauce aus gerösteten Tomaten, getrockneten Paprika, gerösteten Nüssen und Olivenöl, verwendet zu Calçots, Fisch und Gemüse.',
    'Picada': 'Picada',
    'is a paste of fried bread, almonds, garlic, herbs and sometimes chocolate, stirred into stews and soups at the end of cooking to thicken and deepen the flavour.': 'ist eine Paste aus gebratenem Brot, Mandeln, Knoblauch, Kräutern und manchmal Schokolade, die am Ende des Kochens in Eintöpfe und Suppen gerührt wird, um sie zu binden und das Aroma zu vertiefen.',
    'Catalan Wine and Cava': 'Katalanischer Wein und Cava',
    "Catalunya produces some of Spain's finest wines across eleven DO (Denominació d'Origen) zones. The Penedès region is the spiritual home of": "Katalonien produziert einige der besten Weine Spaniens in elf DO-Zonen (Denominació d'Origen). Die Region Penedès ist die spirituelle Heimat des",
    'Cava': 'Cava',
    ", Spain's celebrated sparkling wine made by the traditional method. The Priorat DO produces powerful, mineral reds from ancient Grenache and Carignan vines growing in slate soils. Empordà, the DO closest to Tamariu, produces fresh whites and increasingly impressive reds from the foothills of the Cap de Creus.": ', Spaniens gefeiertem Schaumwein, hergestellt nach der traditionellen Methode. Die DO Priorat erzeugt kraftvolle, mineralische Rotweine aus alten Grenache- und Carignan-Reben, die auf Schieferböden wachsen. Empordà, die Tamariu am nächsten gelegene DO, erzeugt frische Weißweine und zunehmend beeindruckende Rotweine aus den Ausläufern des Cap de Creus.',
    'Eating Habits and Meal Times': 'Essgewohnheiten und Essenszeiten',
    'Catalans eat late by northern European standards. Lunch — the main meal of the day — begins no earlier than 14:00 and often runs to 16:00. Dinner rarely starts before 21:00. A typical day begins with coffee and pastry, followed by a mid-morning snack, a long lunch, a late-afternoon merienda (snack), and dinner. This rhythm is deeply cultural and worth embracing during your stay.': 'Katalanen essen nach nordeuropäischen Maßstäben spät. Das Mittagessen — die Hauptmahlzeit des Tages — beginnt nicht vor 14:00 Uhr und zieht sich oft bis 16:00 Uhr. Das Abendessen beginnt selten vor 21:00 Uhr. Ein typischer Tag beginnt mit Kaffee und Gebäck, gefolgt von einem Snack am Vormittag, einem langen Mittagessen, einer Merienda (Snack) am späten Nachmittag und dem Abendessen. Dieser Rhythmus ist tief kulturell verankert und lohnt es, sich während Ihres Aufenthalts darauf einzulassen.',
    'Tamariu, Costa Brava, Catalunya': 'Tamariu, Costa Brava, Katalonien',
    'Catalonian Language — Tamariu Chalet': 'Katalanische Sprache — Tamariu Chalet',
    'Origins and History': 'Ursprünge und Geschichte',
    'Catalan (': 'Katalanisch (',
    'català': 'català',
    ') is a Romance language descended directly from Vulgar Latin. It developed in the eastern Pyrenean region during the 9th and 10th centuries alongside the emergence of the County of Barcelona. Closely related to Occitan and French, it shares more with those languages than with Castilian Spanish, despite centuries of political union with Spain.': ') ist eine romanische Sprache, die direkt vom Vulgärlatein abstammt. Sie entwickelte sich im 9. und 10. Jahrhundert in der östlichen Pyrenäenregion, zeitgleich mit dem Entstehen der Grafschaft Barcelona. Eng verwandt mit dem Okzitanischen und dem Französischen, teilt sie mehr mit diesen Sprachen als mit dem kastilischen Spanisch, trotz jahrhundertelanger politischer Union mit Spanien.',
    'Catalan enjoyed a golden age during the 12th–15th centuries, producing great literature, poetry and legal texts. Ramon Llull (1232–1316) was among the first European writers to use a vernacular language for philosophy and science.': 'Das Katalanische erlebte im 12.–15. Jahrhundert ein goldenes Zeitalter und brachte große Literatur, Poesie und Rechtstexte hervor. Ramon Llull (1232–1316) gehörte zu den ersten europäischen Autoren, die eine Volkssprache für Philosophie und Wissenschaft verwendeten.',
    'Following the War of the Spanish Succession (1714), Philip V abolished Catalan institutions and suppressed the language in public life. The 19th century Renaixença (Renaissance) movement revived Catalan literature and cultural pride. Under Franco (1939–1975), Catalan was banned in schools, government and public spaces — yet it survived in homes, churches and whispered conversations. Since the restoration of democracy, Catalan has been fully rehabilitated and is today the co-official language of Catalunya, Valencia (as Valencian) and the Balearic Islands.': 'Nach dem Spanischen Erbfolgekrieg (1714) schaffte Philipp V. die katalanischen Institutionen ab und unterdrückte die Sprache im öffentlichen Leben. Die Renaixença-Bewegung (Wiedergeburt) des 19. Jahrhunderts belebte die katalanische Literatur und den kulturellen Stolz wieder. Unter Franco (1939–1975) war Katalanisch in Schulen, Verwaltung und im öffentlichen Raum verboten — doch es überlebte in Häusern, Kirchen und geflüsterten Gesprächen. Seit der Wiederherstellung der Demokratie ist Katalanisch vollständig rehabilitiert und heute die gemeinsame Amtssprache Kataloniens, Valencias (als Valencianisch) und der Balearen.',
    'Today approximately': 'Heute sprechen etwa',
    '10 million people': '10 Millionen Menschen',
    'speak Catalan as their first language. It is the official language of Andorra and is spoken in parts of southern France, Sardinia and the Valencian Community. It is the only official language of Andorra.': 'Katalanisch als ihre Muttersprache. Es ist die Amtssprache Andorras und wird in Teilen Südfrankreichs, Sardiniens und der Valencianischen Gemeinschaft gesprochen. Es ist die einzige Amtssprache Andorras.',
    'Polite Conversation': 'Höfliche Konversation',
    'English': 'Deutsch',
    'Català': 'Català',
    'Pronunciation guide': 'Aussprache',
    'Hello': 'Hallo',
    'Hola': 'Hola',
    'OH-lah': 'OH-lah',
    'Good morning': 'Guten Morgen',
    'Bon dia': 'Bon dia',
    'bohn DEE-ah': 'bohn DEE-ah',
    'Good afternoon': 'Guten Tag',
    'Bona tarda': 'Bona tarda',
    'BOH-nah TAR-dah': 'BOH-nah TAR-dah',
    'Good evening / night': 'Guten Abend / Gute Nacht',
    'Bona nit': 'Bona nit',
    'BOH-nah neet': 'BOH-nah neet',
    'Goodbye': 'Auf Wiedersehen',
    'Adéu': 'Adéu',
    'ah-DAY-oo': 'ah-DAY-oo',
    'See you later': 'Bis später',
    'Fins aviat': 'Fins aviat',
    'feens ah-vee-AHT': 'feens ah-vee-AHT',
    'Please': 'Bitte',
    'Si us plau': 'Si us plau',
    'see oos PLOW': 'see oos PLOW',
    'Thank you': 'Danke',
    'Gràcies': 'Gràcies',
    'GRAH-see-es': 'GRAH-see-es',
    "You're welcome": 'Gern geschehen',
    'De res': 'De res',
    'deh ress': 'deh ress',
    'Excuse me / Sorry': 'Entschuldigung',
    'Perdona': 'Perdona',
    'pear-DOH-nah': 'pear-DOH-nah',
    'Yes': 'Ja',
    'Sí': 'Sí',
    'see': 'see',
    'No': 'Nein',
    'noh': 'noh',
    'Do you speak English?': 'Sprechen Sie Englisch?',
    'Parles anglès?': 'Parles anglès?',
    'PAR-les ang-LESS?': 'PAR-les ang-LESS?',
    "I don't understand": 'Ich verstehe nicht',
    'No entenc': 'No entenc',
    'noh en-TENK': 'noh en-TENK',
    'Where is…?': 'Wo ist…?',
    'On és…?': 'On és…?',
    'ohn ess?': 'ohn ess?',
    'How much does it cost?': 'Wie viel kostet das?',
    'Quant costa?': 'Quant costa?',
    'kwant KOS-tah?': 'kwant KOS-tah?',
    'Cheers!': 'Prost!',
    'Salut!': 'Salut!',
    'sah-LOOT': 'sah-LOOT',
    'Enjoy your meal!': 'Guten Appetit!',
    'Bon profit!': 'Bon profit!',
    'bohn proh-FEET': 'bohn proh-FEET',
    'Numbers': 'Zahlen',
    'Number': 'Zahl',
    'Un / Una': 'Un / Una',
    'Onze': 'Onze',
    'Dos / Dues': 'Dos / Dues',
    'Dotze': 'Dotze',
    'Tres': 'Tres',
    'Vint': 'Vint',
    'Quatre': 'Quatre',
    'Trenta': 'Trenta',
    'Cinc': 'Cinc',
    'Quaranta': 'Quaranta',
    'Sis': 'Sis',
    'Cinquanta': 'Cinquanta',
    'Set': 'Set',
    'Cent': 'Cent',
    'Vuit': 'Vuit',
    'Mil': 'Mil',
    'Nou': 'Nou',
    'Un milió': 'Un milió',
    'Deu': 'Deu',
    'Zero': 'Zero',
    'Days of the Week': 'Wochentage',
    'Monday': 'Montag',
    'Dilluns': 'Dilluns',
    'Tuesday': 'Dienstag',
    'Dimarts': 'Dimarts',
    'Wednesday': 'Mittwoch',
    'Dimecres': 'Dimecres',
    'Thursday': 'Donnerstag',
    'Dijous': 'Dijous',
    'Friday': 'Freitag',
    'Divendres': 'Divendres',
    'Saturday': 'Samstag',
    'Dissabte': 'Dissabte',
    'Sunday': 'Sonntag',
    'Diumenge': 'Diumenge',
    'Months of the Year': 'Monate des Jahres',
    'January': 'Januar',
    'Gener': 'Gener',
    'July': 'Juli',
    'Juliol': 'Juliol',
    'February': 'Februar',
    'Febrer': 'Febrer',
    'Agost': 'Agost',
    'March': 'März',
    'Març': 'Març',
    'September': 'September',
    'Setembre': 'Setembre',
    'April': 'April',
    'Abril': 'Abril',
    'October': 'Oktober',
    'Octubre': 'Octubre',
    'May': 'Mai',
    'Maig': 'Maig',
    'November': 'November',
    'Novembre': 'Novembre',
    'June': 'Juni',
    'Juny': 'Juny',
    'December': 'Dezember',
    'Desembre': 'Desembre',
    'Useful Phrases for Visitors': 'Nützliche Redewendungen für Besucher',
    'Situation': 'Situation',
    'At a restaurant': 'Im Restaurant',
    'A table for two, please': 'Einen Tisch für zwei, bitte',
    'Una taula per a dos, si us plau': 'Una taula per a dos, si us plau',
    'The bill, please': 'Die Rechnung, bitte',
    'El compte, si us plau': 'El compte, si us plau',
    'Shopping': 'Einkaufen',
    'How much is this?': 'Wie viel kostet das?',
    'Quant val això?': 'Quant val això?',
    'I would like…': 'Ich hätte gern…',
    'Voldria…': 'Voldria…',
    'Directions': 'Wegbeschreibung',
    'Straight ahead': 'Geradeaus',
    'Tot recte': 'Tot recte',
    'Turn left / right': 'Links / rechts abbiegen',
    "Gira a l'esquerra / la dreta": "Gira a l'esquerra / la dreta",
    'Emergency': 'Notfall',
    'Help!': 'Hilfe!',
    'Ajuda!': 'Ajuda!',
    'Call a doctor': 'Rufen Sie einen Arzt',
    'Crideu un metge': 'Crideu un metge',
    'Where is the beach?': 'Wo ist der Strand?',
    'On és la platja?': 'On és la platja?',
    'General': 'Allgemein',
    'Very good / Delicious': 'Sehr gut / Köstlich',
    'Molt bo / Boníssim': 'Molt bo / Boníssim',
    'Catalonian Culture — Tamariu Chalet': 'Katalanische Kultur — Tamariu Chalet',
    'A Distinct Identity': 'Eine eigenständige Identität',
    'Catalan culture is one of the most distinctive in Western Europe — shaped by geography, a unique language, centuries of political struggle and a fierce collective pride. Catalans see themselves as a separate nation with its own traditions, values and outlook, and this identity permeates daily life in a way that is immediately apparent to any visitor.': 'Die katalanische Kultur ist eine der eigenständigsten Westeuropas — geprägt von Geografie, einer einzigartigen Sprache, Jahrhunderten politischen Kampfes und einem starken kollektiven Stolz. Katalanen sehen sich als eigene Nation mit eigenen Traditionen, Werten und Sichtweisen, und diese Identität durchdringt das tägliche Leben auf eine Weise, die jedem Besucher sofort auffällt.',
    'Unlike many European regional cultures, Catalan identity has not faded into folklore. It is a living, dynamic force expressed in architecture, sport, food, language and public celebration.': 'Anders als viele europäische Regionalkulturen ist die katalanische Identität nicht zur Folklore verblasst. Sie ist eine lebendige, dynamische Kraft, die sich in Architektur, Sport, Essen, Sprache und öffentlichen Festen ausdrückt.',
    'Castellers — Human Towers': 'Castellers — Menschentürme',
    'Among the most extraordinary cultural traditions anywhere in the world,': 'Zu den außergewöhnlichsten kulturellen Traditionen weltweit gehört, dass',
    'castellers': 'castellers',
    'build human towers (': 'Menschentürme bauen (',
    'castells': 'castells',
    ') that can reach up to ten storeys high. Teams of hundreds of people form a dense human base (': '), die bis zu zehn Stockwerke hoch werden können. Teams aus Hunderten von Menschen bilden eine dichte menschliche Basis (',
    'pinya': 'pinya',
    ') from which columns of climbers rise, with a small child (': '), aus der Säulen von Kletternden aufsteigen, wobei ein kleines Kind (',
    'enxaneta': 'enxaneta',
    ') completing the tower at the top and raising four fingers — a symbol of the Catalan flag.': ') den Turm oben vollendet und vier Finger hebt — ein Symbol der katalanischen Flagge.',
    "The tradition originated in the 18th century and is concentrated in southern Catalunya. It is practised at festivals throughout the year and was inscribed on UNESCO's Intangible Cultural Heritage list in 2010. It is not a spectacle but a community act — participated in by grandparents, parents and grandchildren together.": 'Die Tradition entstand im 18. Jahrhundert und konzentriert sich auf den Süden Kataloniens. Sie wird bei Festen das ganze Jahr über ausgeübt und wurde 2010 in die UNESCO-Liste des immateriellen Kulturerbes aufgenommen. Es ist kein Spektakel, sondern ein Gemeinschaftsakt — an dem Großeltern, Eltern und Enkel gemeinsam teilnehmen.',
    'Sardana — The National Dance': 'Sardana — Der Nationaltanz',
    'The': 'Die',
    'sardana': 'sardana',
    'is a circle dance performed to the accompaniment of a': 'ist ein Kreistanz, der zur Begleitung einer',
    'cobla': 'cobla',
    'band. It appears deceptively simple — dancers of all ages join hands in an expanding circle, performing precise, measured steps — but the counting and execution require concentration and practice. It is danced in town squares throughout Catalunya, particularly on Sundays and during festivals, and anyone may join. The sardana is seen as a democratic dance: no one leads, no one follows, and the circle is always open.': '-Kapelle aufgeführt wird. Er wirkt trügerisch einfach — Tänzer aller Altersgruppen fassen sich in einem wachsenden Kreis an den Händen und führen präzise, abgemessene Schritte aus — doch das Zählen und die Ausführung erfordern Konzentration und Übung. Er wird auf Dorfplätzen in ganz Katalonien getanzt, besonders sonntags und bei Festen, und jeder darf mitmachen. Die Sardana gilt als demokratischer Tanz: niemand führt, niemand folgt, und der Kreis ist immer offen.',
    'Gegants and Bestiari': 'Gegants und Bestiari',
    'Every Catalan town has its': 'Jede katalanische Stadt hat ihre',
    'gegants': 'gegants',
    '— enormous papier-mâché figures, typically 3–4 metres tall, representing historical, mythological or local characters. At festivals, these giants are carried through the streets in a stately, swaying dance. Accompanying them are fire-breathing creatures (': '— riesige Pappmaché-Figuren, typischerweise 3–4 Meter hoch, die historische, mythologische oder lokale Gestalten darstellen. Bei Festen werden diese Riesen in einem gemächlichen, wiegenden Tanz durch die Straßen getragen. Begleitet werden sie von feuerspeienden Kreaturen (',
    'bestiari': 'bestiari',
    ') — dragons, eagles, lions — and the terrifying': ') — Drachen, Adler, Löwen — und dem furchterregenden',
    'correfoc': 'correfoc',
    'or fire run, in which groups dressed as devils charge through the streets with fireworks.': 'oder Feuerlauf, bei dem als Teufel verkleidete Gruppen mit Feuerwerk durch die Straßen stürmen.',
    'Sant Jordi — The Day of the Rose and the Book': 'Sant Jordi — Der Tag der Rose und des Buches',
    "23rd April, the feast of Sant Jordi (Saint George, patron of Catalunya), is the most romantically Catalan of all celebrations. Men give women roses; women give men books. The streets fill with flower stalls and bookshops overflow onto pavements. Barcelona's Rambla and Passeig de Gràcia become rivers of red roses. The tradition predates Valentine's Day by centuries and was chosen by UNESCO as World Book Day in recognition of its significance. For Catalans, the day celebrates both love and culture in equal measure.": 'Der 23. April, das Fest von Sant Jordi (Sankt Georg, Schutzpatron Kataloniens), ist die romantischste aller katalanischen Feiern. Männer schenken Frauen Rosen; Frauen schenken Männern Bücher. Die Straßen füllen sich mit Blumenständen, und Buchläden quellen auf die Gehwege über. Barcelonas Rambla und Passeig de Gràcia werden zu Flüssen aus roten Rosen. Die Tradition ist Jahrhunderte älter als der Valentinstag und wurde von der UNESCO in Anerkennung ihrer Bedeutung zum Welttag des Buches gewählt. Für die Katalanen feiert der Tag Liebe und Kultur zu gleichen Teilen.',
    'FC Barcelona — Més que un Club': 'FC Barcelona — Més que un Club',
    "Football Club Barcelona is far more than a sports team — it is a cultural institution and a symbol of Catalan identity. During the Franco years, when Catalan language and culture were suppressed, the Camp Nou became one of the few places where Catalan could be spoken openly. The club's motto,": 'Der Fußballclub Barcelona ist weit mehr als eine Sportmannschaft — er ist eine kulturelle Institution und ein Symbol katalanischer Identität. Während der Franco-Jahre, als katalanische Sprache und Kultur unterdrückt wurden, wurde das Camp Nou zu einem der wenigen Orte, an denen Katalanisch offen gesprochen werden konnte. Das Motto des Clubs,',
    'Més que un club': 'Més que un club',
    '(More than a club), captures this perfectly. Victories over Real Madrid carry a political charge that visitors from outside the region often find surprising but impossible to miss.': '(Mehr als ein Club), bringt dies perfekt zum Ausdruck. Siege über Real Madrid tragen eine politische Ladung, die Besucher von außerhalb der Region oft überraschend, aber unübersehbar finden.',
    'Modernisme and Architecture': 'Modernisme und Architektur',
    'At the turn of the 20th century, Catalunya produced one of the most distinctive architectural movements in history.': 'Um die Wende zum 20. Jahrhundert brachte Katalonien eine der eigenständigsten Architekturbewegungen der Geschichte hervor.',
    'Catalan Modernisme': 'Katalanischer Modernisme',
    "— the Catalan equivalent of Art Nouveau — expressed national identity through architecture. Its greatest exponent was Antoni Gaudí, whose Sagrada Família, Casa Batlló and Park Güell in Barcelona are among the most visited buildings in the world. Lluís Domènech i Montaner's Palau de la Música Catalana (a UNESCO World Heritage Site) and Hospital de Sant Pau are equally extraordinary.": '— das katalanische Pendant zum Jugendstil — drückte nationale Identität durch Architektur aus. Sein größter Vertreter war Antoni Gaudí, dessen Sagrada Família, Casa Batlló und Park Güell in Barcelona zu den meistbesuchten Gebäuden der Welt zählen. Lluís Domènech i Montaners Palau de la Música Catalana (ein UNESCO-Weltkulturerbe) und das Hospital de Sant Pau sind ebenso außergewöhnlich.',
    'La Diada — National Day': 'La Diada — Nationalfeiertag',
    '11th September marks': 'Der 11. September markiert',
    'La Diada Nacional de Catalunya': 'La Diada Nacional de Catalunya',
    ', the Catalan National Day. It commemorates the fall of Barcelona to Bourbon forces in 1714 and the subsequent abolition of Catalan institutions. Rather than a celebration of victory, it is a day of solemn remembrance and political expression. In recent years, La Diada has been the occasion for massive pro-independence demonstrations, with hundreds of thousands forming human chains across the country.': ', den katalanischen Nationalfeiertag. Er erinnert an den Fall Barcelonas an die bourbonischen Truppen im Jahr 1714 und die anschließende Abschaffung der katalanischen Institutionen. Statt einer Siegesfeier ist es ein Tag des feierlichen Gedenkens und des politischen Ausdrucks. In den letzten Jahren war die Diada Anlass für massive Demonstrationen für die Unabhängigkeit, bei denen Hunderttausende Menschenketten durch das Land bildeten.',
    'Festivals and Celebrations': 'Feste und Feiern',
    'The Catalan festive calendar is rich and varied.': 'Der katalanische Festkalender ist reich und vielfältig.',
    'La Mercè': 'La Mercè',
    "(24 September) is Barcelona's largest annual festival, featuring free concerts, human towers, fire runs and gegants.": '(24. September) ist Barcelonas größtes jährliches Fest, mit kostenlosen Konzerten, Menschentürmen, Feuerläufen und Gegants.',
    'Gràcia Festival': 'Gràcia-Fest',
    "in August sees Barcelona's Gràcia neighbourhood transform into an explosion of elaborately decorated streets. Local villages throughout the Costa Brava celebrate their": 'im August verwandelt Barcelonas Viertel Gràcia in eine Explosion aufwendig geschmückter Straßen. Lokale Dörfer entlang der Costa Brava feiern ihre',
    'festa major': 'festa major',
    'in summer with dancing, fireworks, and sardanes that last through the night.': 'im Sommer mit Tanz, Feuerwerk und Sardanes, die die ganze Nacht dauern.',
    'Catalonian History — Tamariu Chalet': 'Katalanische Geschichte — Tamariu Chalet',
    'Prehistoric and Pre-Roman Catalunya': 'Prähistorisches und vorrömisches Katalonien',
    'The territory that is now Catalunya has been inhabited since the Palaeolithic period — evidence of human presence dates back more than 200,000 years. By the first millennium BC, Iberian peoples had established sophisticated settlements along the coast and inland valleys. The Greeks founded the colony of': 'Das Gebiet des heutigen Kataloniens ist seit dem Paläolithikum bewohnt — Belege menschlicher Präsenz reichen über 200.000 Jahre zurück. Im ersten Jahrtausend v. Chr. hatten iberische Völker entlang der Küste und in den Tälern des Landesinneren hoch entwickelte Siedlungen gegründet. Die Griechen gründeten die Kolonie',
    'Empúries': 'Empúries',
    '(Emporion) on the Costa Brava around 575 BC — its remarkable ruins survive and are visible from Tamariu. The Carthaginians were also active in the region, and it was through here that Hannibal is said to have marched his army towards Rome in 218 BC.': '(Emporion) an der Costa Brava um 575 v. Chr. — ihre bemerkenswerten Ruinen sind erhalten und von Tamariu aus sichtbar. Auch die Karthager waren in der Region aktiv, und durch dieses Gebiet soll Hannibal 218 v. Chr. seine Armee Richtung Rom geführt haben.',
    'Roman Hispania (218 BC – 5th century AD)': 'Römisches Hispanien (218 v. Chr. – 5. Jahrhundert n. Chr.)',
    'Rome invaded the Iberian Peninsula in 218 BC and made the northeast its base of operations.': 'Rom fiel 218 v. Chr. in die Iberische Halbinsel ein und machte den Nordosten zu seinem Operationsstützpunkt.',
    'Tarraco': 'Tarraco',
    '(modern Tarragona) became the capital of the province of Hispania Citerior and one of the most important cities in the western Roman Empire. Its amphitheatre, circus and city walls survive to this day and are designated UNESCO World Heritage Sites. Roman roads, bridges and aqueducts shaped the landscape of Catalunya for centuries. Latin — the language of the colonisers — evolved into Catalan over the following centuries of Visigothic rule and early medieval settlement.': '(das heutige Tarragona) wurde die Hauptstadt der Provinz Hispania Citerior und eine der wichtigsten Städte des westlichen Römischen Reiches. Sein Amphitheater, der Zirkus und die Stadtmauern sind bis heute erhalten und als UNESCO-Weltkulturerbe ausgewiesen. Römische Straßen, Brücken und Aquädukte prägten die Landschaft Kataloniens über Jahrhunderte. Das Latein — die Sprache der Kolonisatoren — entwickelte sich in den folgenden Jahrhunderten westgotischer Herrschaft und frühmittelalterlicher Besiedlung zum Katalanischen.',
    'Visigothic Rule and Moorish Conquest': 'Westgotische Herrschaft und maurische Eroberung',
    'With the collapse of the Western Roman Empire in the 5th century, the Visigoths took control of the peninsula. Their capital was Toledo but they maintained a significant presence in Hispania Citerior. In': 'Mit dem Zusammenbruch des Weströmischen Reiches im 5. Jahrhundert übernahmen die Westgoten die Kontrolle über die Halbinsel. Ihre Hauptstadt war Toledo, doch sie hielten eine bedeutende Präsenz in Hispania Citerior. Im Jahr',
    '711 AD': '711 n. Chr.',
    ', Moorish forces crossed from North Africa and within seven years had conquered most of the Iberian Peninsula, including what is now Catalunya. However, Moorish control of the northeast was relatively brief — Frankish forces under Charlemagne recaptured Barcelona in': ', überquerten maurische Truppen aus Nordafrika, und binnen sieben Jahren hatten sie den Großteil der Iberischen Halbinsel erobert, einschließlich des heutigen Kataloniens. Die maurische Kontrolle über den Nordosten war jedoch relativ kurz — fränkische Truppen unter Karl dem Großen eroberten Barcelona im Jahr',
    '801 AD': '801 n. Chr.',
    ', establishing the Hispanic March as a buffer zone between the Frankish Empire and Al-Andalus.': 'zurück und errichteten die Spanische Mark als Pufferzone zwischen dem Fränkischen Reich und Al-Andalus.',
    'The County of Barcelona and the Birth of Catalunya': 'Die Grafschaft Barcelona und die Geburt Kataloniens',
    'From the Carolingian March, a series of independent counties gradually emerged. The': 'Aus der karolingischen Mark ging allmählich eine Reihe unabhängiger Grafschaften hervor. Die',
    'County of Barcelona': 'Grafschaft Barcelona',
    'grew dominant under Guifré el Pilós (Wilfred the Hairy, c.840–897), who is considered the founding father of Catalunya. Legend holds that when Wilfred was wounded in battle, the Frankish king drew four fingers of blood across his golden shield — creating the four red stripes on gold that remain the Catalan flag (': 'wurde unter Guifré el Pilós (Wilfried der Haarige, ca. 840–897) dominant, der als Gründervater Kataloniens gilt. Der Legende nach zog der fränkische König, als Wilfried in der Schlacht verwundet wurde, vier blutige Finger über seinen goldenen Schild — und schuf so die vier roten Streifen auf Gold, die bis heute die katalanische Flagge sind (',
    'la Senyera': 'la Senyera',
    ') to this day.': ').',
    'In 988, Count Borrell II broke ties with the Frankish crown, effectively making the County of Barcelona an independent state. The name': '988 brach Graf Borrell II. die Bindungen zur fränkischen Krone und machte die Grafschaft Barcelona faktisch zu einem unabhängigen Staat. Der Name',
    'Catalunya': 'Catalunya',
    'first appears in documents from around 1115.': 'erscheint erstmals in Dokumenten um 1115.',
    'The Crown of Aragon (1137–1469)': 'Die Krone von Aragón (1137–1469)',
    'In 1137, the County of Barcelona united with the Kingdom of Aragon through marriage, forming the': '1137 vereinigte sich die Grafschaft Barcelona durch Heirat mit dem Königreich Aragón und bildete die',
    'Crown of Aragon': 'Krone von Aragón',
    '— a powerful federation that would expand to include Valencia, the Balearic Islands, Sicily, Sardinia, Naples and briefly Athens. The 13th and 14th centuries were a golden age for Catalan commerce, culture and language. Barcelona became one of the great trading cities of the Mediterranean, and the': '— eine mächtige Föderation, die sich um Valencia, die Balearen, Sizilien, Sardinien, Neapel und kurzzeitig Athen erweitern sollte. Das 13. und 14. Jahrhundert waren ein goldenes Zeitalter für katalanischen Handel, Kultur und Sprache. Barcelona wurde eine der großen Handelsstädte des Mittelmeers, und die',
    'Corts Catalanes': 'Corts Catalanes',
    '(Catalan Parliament) was among the earliest representative assemblies in Europe.': '(katalanisches Parlament) gehörten zu den frühesten repräsentativen Versammlungen Europas.',
    'Union with Castile and the War of Succession': 'Union mit Kastilien und der Erbfolgekrieg',
    'In 1469, Ferdinand II of Aragon married Isabella I of Castile, uniting the two kingdoms under one crown. Though it was a personal union rather than a merger, Catalan institutions and laws were gradually eroded over the following centuries. The catastrophic turning point came with the': '1469 heiratete Ferdinand II. von Aragón Isabella I. von Kastilien und vereinte die beiden Königreiche unter einer Krone. Obwohl es eine Personalunion statt einer Verschmelzung war, wurden die katalanischen Institutionen und Gesetze in den folgenden Jahrhunderten allmählich ausgehöhlt. Der katastrophale Wendepunkt kam mit dem',
    'War of the Spanish Succession': 'Spanischen Erbfolgekrieg',
    '(1701–1714). Catalunya backed the Habsburg claimant against the Bourbon Philip V. On': '(1701–1714). Katalonien unterstützte den habsburgischen Anwärter gegen den Bourbonen Philipp V. Am',
    ', Barcelona fell after a year-long siege. Philip V abolished all Catalan institutions, banned the Catalan language in official life, and imposed Castilian law — a date Catalans commemorate as their National Day to this day.': ', fiel Barcelona nach einjähriger Belagerung. Philipp V. schaffte alle katalanischen Institutionen ab, verbot die katalanische Sprache im offiziellen Leben und verhängte kastilisches Recht — ein Datum, das die Katalanen bis heute als ihren Nationalfeiertag begehen.',
    'The 19th Century: Industrialisation and the Renaixença': 'Das 19. Jahrhundert: Industrialisierung und die Renaixença',
    'Catalunya was the first industrialised region of the Iberian Peninsula, developing a powerful textile industry from the 1820s onwards. The wealth generated by industry fuelled both social conflict and a cultural renaissance. The': 'Katalonien war die erste industrialisierte Region der Iberischen Halbinsel und entwickelte ab den 1820er Jahren eine mächtige Textilindustrie. Der von der Industrie erzeugte Reichtum befeuerte sowohl soziale Konflikte als auch eine kulturelle Renaissance. Die',
    'Renaixença': 'Renaixença',
    "(Rebirth) movement, from the mid-19th century, revived Catalan language and literature after two centuries of suppression. Poets, linguists and historians worked to codify and celebrate Catalan culture. Barcelona's remarkable": '-Bewegung (Wiedergeburt) ab Mitte des 19. Jahrhunderts belebte nach zwei Jahrhunderten der Unterdrückung die katalanische Sprache und Literatur wieder. Dichter, Sprachwissenschaftler und Historiker arbeiteten daran, die katalanische Kultur zu kodifizieren und zu feiern. Barcelonas bemerkenswertes',
    'Eixample': 'Eixample',
    '(Extension) district, designed by Ildefons Cerdà, was laid out from 1860 — one of the great achievements of 19th-century urban planning.': '-Viertel (Erweiterung), entworfen von Ildefons Cerdà, wurde ab 1860 angelegt — eine der großen Leistungen der Stadtplanung des 19. Jahrhunderts.',
    'The 20th Century: Republic, Civil War and Dictatorship': 'Das 20. Jahrhundert: Republik, Bürgerkrieg und Diktatur',
    "The early 20th century saw the rise of Catalan nationalism alongside workers' movements and anarchism. The Second Spanish Republic (1931–1936) granted Catalunya the Statute of Autonomy, restoring the": 'Das frühe 20. Jahrhundert erlebte den Aufstieg des katalanischen Nationalismus neben Arbeiterbewegungen und Anarchismus. Die Zweite Spanische Republik (1931–1936) gewährte Katalonien das Autonomiestatut und stellte die',
    'Generalitat': 'Generalitat',
    '— its regional government. The Spanish Civil War (1936–1939) was catastrophic. Barcelona was a Republican stronghold and suffered intense bombardment; the city fell in January 1939. Under': '— seine Regionalregierung — wieder her. Der Spanische Bürgerkrieg (1936–1939) war katastrophal. Barcelona war eine republikanische Hochburg und erlitt heftige Bombardierungen; die Stadt fiel im Januar 1939. Unter',
    'Francisco Franco': 'Francisco Franco',
    '(1939–1975), Catalan was banned, cultural organisations dissolved, and thousands of Catalans were imprisoned or executed. The language survived only in private homes and the Catholic Church.': '(1939–1975) war Katalanisch verboten, kulturelle Organisationen wurden aufgelöst, und Tausende Katalanen wurden inhaftiert oder hingerichtet. Die Sprache überlebte nur in privaten Häusern und der katholischen Kirche.',
    'Democracy, Autonomy and the Independence Question': 'Demokratie, Autonomie und die Unabhängigkeitsfrage',
    "Franco's death in 1975 and the transition to democracy brought a rapid rehabilitation of Catalan identity. The 1979 Statute of Autonomy restored the Generalitat and made Catalan the co-official language. Catalan was reintroduced in schools and public life, and the culture experienced a second renaissance. In the 21st century, a growing independence movement has defined Catalan politics. A disputed referendum in October 2017 and its contested aftermath remain unresolved — but they reflect a centuries-old question about identity, sovereignty and belonging that Catalunya has never stopped asking.": 'Francos Tod 1975 und der Übergang zur Demokratie brachten eine rasche Rehabilitierung der katalanischen Identität. Das Autonomiestatut von 1979 stellte die Generalitat wieder her und machte Katalanisch zur gemeinsamen Amtssprache. Katalanisch wurde in Schulen und im öffentlichen Leben wieder eingeführt, und die Kultur erlebte eine zweite Renaissance. Im 21. Jahrhundert prägt eine wachsende Unabhängigkeitsbewegung die katalanische Politik. Ein umstrittenes Referendum im Oktober 2017 und seine umkämpften Folgen bleiben ungelöst — doch sie spiegeln eine jahrhundertealte Frage nach Identität, Souveränität und Zugehörigkeit wider, die Katalonien nie aufgehört hat zu stellen.',
    'Catalonian Cities of Interest — Tamariu Chalet': 'Sehenswerte Städte Kataloniens — Tamariu Chalet',
    'Introduction': 'Einführung',
    'Catalunya is a compact region — roughly the size of Belgium — yet it contains an extraordinary variety of cities and towns, from a great European capital to small medieval market towns. Each reflects a different facet of Catalan history and character. All of the cities below are reachable by car or public transport from Tamariu.': 'Katalonien ist eine kompakte Region — etwa so groß wie Belgien — und enthält doch eine außergewöhnliche Vielfalt an Städten und Ortschaften, von einer großen europäischen Hauptstadt bis zu kleinen mittelalterlichen Marktstädten. Jede spiegelt eine andere Facette der katalanischen Geschichte und Eigenart wider. Alle unten genannten Städte sind von Tamariu aus mit dem Auto oder öffentlichen Verkehrsmitteln erreichbar.',
    'Barcelona': 'Barcelona',
    "The Catalan capital and one of Europe's great cities. Home to Gaudí's Sagrada Família, the Gothic Quarter, the Rambla, Park Güell, Barceloneta beach and world-class food and nightlife. About 2 hours from Tamariu by car.": 'Die katalanische Hauptstadt und eine der großen Städte Europas. Heimat von Gaudís Sagrada Família, dem gotischen Viertel, der Rambla, dem Park Güell, dem Strand Barceloneta und Weltklasse-Gastronomie und -Nachtleben. Etwa 2 Autostunden von Tamariu entfernt.',
    'Girona': 'Girona',
    'The provincial capital, just 45 minutes from Tamariu. Medieval walls, a soaring cathedral, the Jewish quarter (': 'Die Provinzhauptstadt, nur 45 Minuten von Tamariu entfernt. Mittelalterliche Mauern, eine aufragende Kathedrale, das jüdische Viertel (',
    'Call': 'Call',
    '), the River Onyar with its colourful houses, and a remarkable food scene including the world-renowned restaurant El Celler de Can Roca.': '), der Fluss Onyar mit seinen bunten Häusern und eine bemerkenswerte Gastronomieszene, darunter das weltberühmte Restaurant El Celler de Can Roca.',
    'Tarragona': 'Tarragona',
    'Roman Tarraco — a UNESCO World Heritage Site. An amphitheatre on the seafront, a massive circus, Augustan city walls, and a remarkably intact Roman street grid. Also known for its': 'Das römische Tarraco — ein UNESCO-Weltkulturerbe. Ein Amphitheater an der Strandpromenade, ein gewaltiger Zirkus, augusteische Stadtmauern und ein bemerkenswert intaktes römisches Straßenraster. Ebenfalls bekannt für seine',
    'and its annual human towers festival.': 'und sein jährliches Menschenturm-Festival.',
    'Figueres': 'Figueres',
    'Home of Salvador Dalí and his extraordinary Teatre-Museu Dalí — the most visited museum in Spain after the Prado. The town itself is modest, but the museum is unmissable. About 1 hour north of Tamariu.': 'Heimat von Salvador Dalí und seinem außergewöhnlichen Teatre-Museu Dalí — dem meistbesuchten Museum Spaniens nach dem Prado. Die Stadt selbst ist bescheiden, aber das Museum ist unverzichtbar. Etwa 1 Stunde nördlich von Tamariu.',
    'Lleida': 'Lleida',
    'The western capital of Catalunya, dominated by the dramatic Seu Vella — a medieval cathedral built on a hilltop Roman fortress. A less-visited city with a relaxed pace and excellent local food traditions including fine lamb and river fish.': 'Die westliche Hauptstadt Kataloniens, überragt von der dramatischen Seu Vella — einer mittelalterlichen Kathedrale, erbaut auf einer römischen Festung auf einem Hügel. Eine weniger besuchte Stadt mit gemächlichem Tempo und ausgezeichneten lokalen Esstraditionen, darunter feines Lamm und Flussfisch.',
    'Vic': 'Vic',
    'An inland market town famous for its medieval centre, its baroque cathedral frescoes by Josep Maria Sert, and above all its': 'Eine Marktstadt im Landesinneren, berühmt für ihr mittelalterliches Zentrum, die barocken Kathedralenfresken von Josep Maria Sert und vor allem für ihre',
    'embotits': 'embotits',
    '— the finest cured meats and sausages in Catalunya. The Saturday market is one of the best in the region.': '— die feinsten Wurst- und Pökelwaren Kataloniens. Der Samstagsmarkt ist einer der besten der Region.',
    'Sitges': 'Sitges',
    "A charming coastal town south of Barcelona, known for its beautiful beaches, modernista architecture, vibrant LGBTQ+ community and one of Europe's most celebrated carnivals in February. A relaxed contrast to Barcelona's intensity.": 'Eine charmante Küstenstadt südlich von Barcelona, bekannt für ihre schönen Strände, die Modernisme-Architektur, die lebendige LGBTQ+-Community und einen der gefeiertsten Karnevale Europas im Februar. Ein entspannter Kontrast zur Intensität Barcelonas.',
    'Besalú': 'Besalú',
    'One of the best-preserved medieval towns in Spain. Its 12th-century fortified bridge over the River Fluvià is instantly recognisable. The town retains its Jewish quarter, Romanesque churches and ancient street plan — virtually unchanged in 800 years.': 'Eine der besterhaltenen mittelalterlichen Städte Spaniens. Ihre befestigte Brücke aus dem 12. Jahrhundert über den Fluss Fluvià ist sofort erkennbar. Die Stadt bewahrt ihr jüdisches Viertel, romanische Kirchen und den alten Straßenplan — praktisch unverändert seit 800 Jahren.',
    'Montserrat': 'Montserrat',
    'Not a city but an unmissable destination — a serrated mountain massif rising dramatically from the plain, topped by a Benedictine monastery housing the revered Black Madonna. The views are extraordinary and the hiking trails outstanding.': 'Keine Stadt, aber ein unverzichtbares Ziel — ein gezacktes Bergmassiv, das dramatisch aus der Ebene aufragt, gekrönt von einem Benediktinerkloster, das die verehrte Schwarze Madonna beherbergt. Die Ausblicke sind außergewöhnlich und die Wanderwege hervorragend.',
    'Cadaqués': 'Cadaqués',
    'The most beautiful village on the Costa Brava — a whitewashed fishing village on a rocky bay accessible only by a winding mountain road. Dalí lived here for decades. Artists, writers and travellers have been drawn to its light and isolation since the 1960s.': 'Das schönste Dorf der Costa Brava — ein weiß getünchtes Fischerdorf an einer felsigen Bucht, nur über eine kurvenreiche Bergstraße erreichbar. Dalí lebte hier jahrzehntelang. Künstler, Schriftsteller und Reisende zieht es seit den 1960er Jahren zu seinem Licht und seiner Abgeschiedenheit.',
    'Olot': 'Olot',
    'Capital of the volcanic Garrotxa region — a landscape of extinct volcanoes, beech forests and medieval villages. Excellent hiking in the Zona Volcànica Natural Park. The town itself has a remarkable early modernista architectural heritage.': 'Hauptstadt der vulkanischen Region Garrotxa — eine Landschaft aus erloschenen Vulkanen, Buchenwäldern und mittelalterlichen Dörfern. Ausgezeichnetes Wandern im Naturpark Zona Volcànica. Die Stadt selbst hat ein bemerkenswertes frühes Modernisme-Architekturerbe.',
    'Peratallada': 'Peratallada',
    'A perfectly preserved medieval village carved from golden sandstone, just 20 minutes from Tamariu. The castle, walls and cobbled streets are essentially unchanged from the 11th century. An ideal afternoon excursion with excellent restaurants.': 'Ein perfekt erhaltenes mittelalterliches Dorf, aus goldenem Sandstein gehauen, nur 20 Minuten von Tamariu. Die Burg, die Mauern und die Kopfsteinpflasterstraßen sind im Wesentlichen unverändert seit dem 11. Jahrhundert. Ein idealer Nachmittagsausflug mit ausgezeichneten Restaurants.',
    'Day Trips from Tamariu': 'Tagesausflüge von Tamariu',
    "Tamariu's position on the Costa Brava places it within easy reach of much of what Catalunya has to offer. Girona is just 45 minutes away and well worth a full day. Figueres and Cadaqués are an hour north. The medieval villages of the Baix Empordà — Pals, Peratallada, Ullastret with its Iberian ruins — are all within 30 minutes. Barcelona makes a long but entirely manageable day trip at around two hours each way.": 'Tamarius Lage an der Costa Brava bringt es in bequeme Reichweite zu einem Großteil dessen, was Katalonien zu bieten hat. Girona ist nur 45 Minuten entfernt und einen ganzen Tag wert. Figueres und Cadaqués liegen eine Stunde nördlich. Die mittelalterlichen Dörfer des Baix Empordà — Pals, Peratallada, Ullastret mit seinen iberischen Ruinen — sind alle innerhalb von 30 Minuten erreichbar. Barcelona ist ein langer, aber durchaus machbarer Tagesausflug mit etwa zwei Stunden pro Richtung.',
    'Catalonian Facts — Tamariu Chalet': 'Fakten über Katalonien — Tamariu Chalet',
    'Unusual and Surprising Facts about Catalunya': 'Ungewöhnliche und überraschende Fakten über Katalonien',
    'Catalunya is a place of deep contradictions and endearing peculiarities. Beneath the sophisticated exterior of Barcelona and the quiet beauty of the Costa Brava lies a culture full of surprising customs, eccentric traditions and facts that visitors rarely expect. Here are some of the most memorable.': 'Katalonien ist ein Ort tiefer Widersprüche und liebenswerter Eigenheiten. Unter der weltgewandten Fassade Barcelonas und der stillen Schönheit der Costa Brava liegt eine Kultur voller überraschender Bräuche, exzentrischer Traditionen und Fakten, die Besucher selten erwarten. Hier sind einige der einprägsamsten.',
    'The Caga Tió — The Christmas Log': 'Der Caga Tió — Der Weihnachtsklotz',
    'Every Catalan household has a': 'Jeder katalanische Haushalt hat einen',
    'Tió de Nadal': 'Tió de Nadal',
    '— a hollow log with a smiling painted face and a little red hat. From 8th December, children feed it scraps of food each night. On Christmas Eve, they beat it with sticks while singing a song, demanding it "defecate" gifts. It does — sweets, nuts and small presents hidden inside. Possibly the most unusual Christmas tradition in Europe.': '— einen hohlen Holzklotz mit lächelndem aufgemaltem Gesicht und einer kleinen roten Mütze. Ab dem 8. Dezember füttern ihn Kinder jeden Abend mit Essensresten. An Heiligabend schlagen sie ihn mit Stöcken, während sie ein Lied singen, und verlangen, dass er Geschenke „ausscheidet". Das tut er — Süßigkeiten, Nüsse und kleine Geschenke, die im Inneren versteckt sind. Vielleicht die ungewöhnlichste Weihnachtstradition Europas.',
    'El Caganer — The Christmas Defecator': 'El Caganer — Der Weihnachtsscheißer',
    'Catalan nativity scenes (': 'Katalanische Krippen (',
    'pessebres': 'pessebres',
    ') include all the standard figures — but tucked away in a corner is the': ') enthalten alle üblichen Figuren — doch in einer Ecke versteckt sitzt der',
    'caganer': 'caganer',
    ': a small figure squatting with his trousers around his ankles. Traditionally a peasant, modern caganers come as politicians, celebrities, footballers and even popes. Far from being considered rude, the caganer is considered a symbol of good luck and equality — he fertilises the earth.': ': eine kleine Figur, die mit heruntergelassener Hose hockt. Traditionell ein Bauer, kommen moderne Caganers als Politiker, Prominente, Fußballer und sogar Päpste daher. Weit davon entfernt, als anstößig zu gelten, wird der Caganer als Symbol für Glück und Gleichheit betrachtet — er düngt die Erde.',
    'Catalan is Spoken in Four Countries': 'Katalanisch wird in vier Ländern gesprochen',
    "Catalan is the official language of Andorra and is spoken in parts of France (Roussillon), Italy (Sardinia's Alghero) and Spain (Catalunya, Valencia, Balearic Islands). With around 10 million speakers, it is the 8th most spoken language in the European Union.": 'Katalanisch ist die Amtssprache Andorras und wird in Teilen Frankreichs (Roussillon), Italiens (Alghero auf Sardinien) und Spaniens (Katalonien, Valencia, Balearen) gesprochen. Mit rund 10 Millionen Sprechern ist es die achthäufigste Sprache in der Europäischen Union.',
    'Human Towers are UNESCO Heritage': 'Menschentürme sind UNESCO-Erbe',
    'Castellers': 'Castellers',
    "— human towers reaching 10 storeys — were inscribed on UNESCO's Intangible Cultural Heritage list in 2010. The tradition is entirely non-competitive in spirit; teams (": '— Menschentürme, die 10 Stockwerke erreichen — wurden 2010 in die UNESCO-Liste des immateriellen Kulturerbes aufgenommen. Die Tradition ist im Geiste völlig unwettbewerblich; Teams (',
    'colles castelleres': 'colles castelleres',
    ') judge themselves by their own standards. A tower is not complete until the': ') beurteilen sich nach ihren eigenen Maßstäben. Ein Turm ist erst vollständig, wenn der',
    '— always a small child — reaches the top.': '— immer ein kleines Kind — die Spitze erreicht.',
    'Catalunya Was Not Always Part of Spain': 'Katalonien war nicht immer Teil Spaniens',
    'The political union of Catalunya with Castile came through marriage in 1469, but Catalunya retained its own institutions, laws and parliament for another 245 years — until they were abolished after the War of the Spanish Succession in 1714. Catalans have never fully accepted that this was a legitimate union.': 'Die politische Union Kataloniens mit Kastilien kam 1469 durch Heirat zustande, doch Katalonien behielt seine eigenen Institutionen, Gesetze und sein Parlament weitere 245 Jahre — bis sie nach dem Spanischen Erbfolgekrieg 1714 abgeschafft wurden. Die Katalanen haben nie ganz akzeptiert, dass dies eine legitime Union war.',
    'The Catalan Flag is One of the Oldest in the World': 'Die katalanische Flagge ist eine der ältesten der Welt',
    'Senyera': 'Senyera',
    '— four red stripes on gold — is first documented in the 12th century, making it one of the oldest flags in continuous use anywhere in the world. Legend attributes it to Wilfred the Hairy, though historians are somewhat sceptical of the romantic story involving royal blood on a golden shield.': '— vier rote Streifen auf Gold — ist erstmals im 12. Jahrhundert dokumentiert und damit eine der ältesten durchgehend verwendeten Flaggen der Welt. Die Legende schreibt sie Wilfried dem Haarigen zu, obwohl Historiker der romantischen Geschichte mit königlichem Blut auf einem goldenen Schild eher skeptisch gegenüberstehen.',
    'Barcelona Has Its Own Time Zone Quirk': 'Barcelona hat eine eigene Zeitzonen-Kuriosität',
    'Geographically, Barcelona sits at roughly the same longitude as London and should logically be in the UTC+0 time zone. However, Franco aligned Spain with Nazi Germany\'s time zone during World War II, moving the clocks forward one hour — where they have remained ever since. Catalans go to bed later than almost anyone in Europe partly because their "midnight" is geographically closer to 11pm.': 'Geografisch liegt Barcelona ungefähr auf demselben Längengrad wie London und müsste logischerweise in der Zeitzone UTC+0 liegen. Franco richtete Spanien jedoch während des Zweiten Weltkriegs nach der Zeitzone Nazi-Deutschlands aus und stellte die Uhren eine Stunde vor — wo sie seither geblieben sind. Katalanen gehen später zu Bett als fast alle in Europa, teils weil ihre „Mitternacht" geografisch näher an 23 Uhr liegt.',
    "The World's First Literary Prize for Women": 'Der weltweit erste Literaturpreis für Frauen',
    'Jocs Florals': 'Jocs Florals',
    ", revived in Barcelona in 1859 during the Renaixença, were the world's first literary competition to award prizes specifically to women poets. The tradition of awarding a rose to the winner survives in Sant Jordi celebrations today.": ', 1859 in Barcelona während der Renaixença wiederbelebt, waren der weltweit erste Literaturwettbewerb, der Preise gezielt an Dichterinnen vergab. Die Tradition, der Gewinnerin eine Rose zu verleihen, überlebt heute in den Sant-Jordi-Feiern.',
    'Gaudí Was Almost Nobody': 'Gaudí war fast ein Niemand',
    'When Antoni Gaudí died in 1926 — hit by a tram because he looked so shabby that taxi drivers assumed he was a beggar and refused to stop — he was buried in the crypt of the Sagrada Família, which had then been under construction for 44 years. It is still unfinished today, over a century after his death, and is the most visited building in Spain.': 'Als Antoni Gaudí 1926 starb — von einer Straßenbahn erfasst, weil er so schäbig aussah, dass Taxifahrer ihn für einen Bettler hielten und nicht anhielten — wurde er in der Krypta der Sagrada Família bestattet, die damals seit 44 Jahren im Bau war. Sie ist bis heute unvollendet, über ein Jahrhundert nach seinem Tod, und ist das meistbesuchte Gebäude Spaniens.',
    'The Correfoc: Running With Fire': 'Der Correfoc: Laufen mit Feuer',
    '(fire run) is perhaps the most visceral Catalan tradition. Groups dressed as devils charge through streets with handheld fireworks and fire-spewing dragon figures, while crowds dance among the sparks. Participants are advised to wear old, synthetic-free clothing. It is terrifying, exhilarating and utterly Catalan.': '(Feuerlauf) ist vielleicht die viszeralste katalanische Tradition. Als Teufel verkleidete Gruppen stürmen mit Handfeuerwerk und feuerspeienden Drachenfiguren durch die Straßen, während Menschenmengen zwischen den Funken tanzen. Teilnehmern wird geraten, alte, synthetikfreie Kleidung zu tragen. Es ist furchterregend, berauschend und durch und durch katalanisch.',
    'Catalan Sardines are Not What You Think': 'Katalanische Sardinen sind nicht, was Sie denken',
    'The feast of Sant Joan (Midsummer, 23–24 June) is celebrated across Catalunya with bonfires, fireworks and the communal grilling of sardines on the beach —': 'Das Fest von Sant Joan (Mittsommer, 23.–24. Juni) wird in ganz Katalonien mit Freudenfeuern, Feuerwerk und dem gemeinschaftlichen Grillen von Sardinen am Strand gefeiert —',
    'espinagada de sardines': 'espinagada de sardines',
    '. In Tamariu and every coastal village, families gather on the beach at midnight to eat sardines and watch the fireworks. It is among the most magical nights of the Catalan year.': '. In Tamariu und jedem Küstendorf versammeln sich Familien um Mitternacht am Strand, um Sardinen zu essen und das Feuerwerk zu beobachten. Es gehört zu den magischsten Nächten des katalanischen Jahres.',
    'Three Great Artists Born in Catalunya': 'Drei große Künstler, in Katalonien geboren',
    'Salvador Dalí (Figueres), Joan Miró (Barcelona), and Antoni Gaudí (Reus) were all Catalan. Their work collectively spans surrealism, abstract expressionism and organic architecture — and all three drew directly on Catalan landscape, culture and identity as the source of their vision.': 'Salvador Dalí (Figueres), Joan Miró (Barcelona) und Antoni Gaudí (Reus) waren alle Katalanen. Ihr Werk umspannt zusammen Surrealismus, abstrakten Expressionismus und organische Architektur — und alle drei schöpften unmittelbar aus katalanischer Landschaft, Kultur und Identität als Quelle ihrer Vision.',
    'A note on identity:': 'Ein Hinweis zur Identität:',
    'When visiting Catalunya, be aware that many locals feel strongly Catalan first and Spanish second — or not Spanish at all. Addressing people in Catalan (even just': 'Wenn Sie Katalonien besuchen, sollten Sie sich bewusst sein, dass viele Einheimische sich in erster Linie stark katalanisch und erst in zweiter Linie spanisch fühlen — oder gar nicht spanisch. Menschen auf Katalanisch anzusprechen (auch nur',
    'hola': 'hola',
    'gràcies': 'gràcies',
    ") is always warmly appreciated, as is showing genuine curiosity about Catalan culture and history. The region's complex identity is not a political abstraction — it is lived daily, and visitors who engage with it respectfully will find an exceptionally warm welcome.": ') wird immer herzlich geschätzt, ebenso wie echtes Interesse an katalanischer Kultur und Geschichte. Die komplexe Identität der Region ist keine politische Abstraktion — sie wird täglich gelebt, und Besucher, die sich respektvoll darauf einlassen, werden einen außergewöhnlich herzlichen Empfang erleben.',
    'Contact &amp; Book — Tamariu Chalet': 'Kontakt &amp; Buchen — Tamariu Chalet',
    'Contact &amp; Booking': 'Kontakt &amp; Buchung',
    'Get in Touch': 'Kontakt aufnehmen',
    'Contact Details': 'Kontaktdaten',
    "We'd love to hear from you — whether you have a question about the accommodation, want to check availability or are ready to book. We aim to respond within 24 hours.": 'Wir freuen uns, von Ihnen zu hören — ob Sie eine Frage zur Unterkunft haben, die Verfügbarkeit prüfen möchten oder bereit sind zu buchen. Wir bemühen uns, innerhalb von 24 Stunden zu antworten.',
    'Email': 'E-Mail',
    'tamariuchalet@gmail.com': 'tamariuchalet@gmail.com',
    'Phone &amp; WhatsApp': 'Telefon &amp; WhatsApp',
    "WhatsApp messages welcome — we'll reply as soon as possible.": 'WhatsApp-Nachrichten willkommen — wir antworten so bald wie möglich.',
    'Address': 'Adresse',
    "Carrer de la Punta De L'Estela 7, Tamariu, Palafrugell": "Carrer de la Punta De L'Estela 7, Tamariu, Palafrugell",
    'Girona, 17212, Spain': 'Girona, 17212, Spanien',
    '💬 WhatsApp Us': '💬 Schreiben Sie uns per WhatsApp',
    '📋 Cancellation Policy': '📋 Stornierungsbedingungen',
    '📋 House Rules': '📋 Hausordnung',
    'Season &amp; Rates Summary': 'Saison- &amp; Preisübersicht',
    '🛏 Rooms (Double &amp; Twin)': '🛏 Zimmer (Doppel &amp; Twin)',
    'Per night': 'Pro Nacht',
    'Min stay': 'Mindestaufenthalt',
    '1 May – 31 May': '1 Mai – 31 Mai',
    '1 Jun – 31 Aug': '1 Jun – 31 Aug',
    'Other': 'Sonstige',
    'Jan–Apr &amp; Sep–Dec': 'Jan–Apr &amp; Sep–Dez',
    'Max 2 guests · cleaning fee €30 per stay': 'Max. 2 Gäste · Reinigungsgebühr 30 € pro Aufenthalt',
    '🏠 Studio Apartment': '🏠 Studio-Apartment',
    '1 Sep – 31 Dec': '1 Sep – 31 Dez',
    'Up to 4 guests · 2 included, extra guests +€50/person/night · cleaning fee €45 per stay': 'Bis zu 4 Gäste · 2 inklusive, zusätzliche Gäste +50 €/Person/Nacht · Reinigungsgebühr 45 € pro Aufenthalt',
    'All rates are per night. Cleaning fee is charged once per stay.': 'Alle Preise gelten pro Nacht. Die Reinigungsgebühr wird einmal pro Aufenthalt berechnet.',
    'Make an Enquiry': 'Eine Anfrage stellen',
    "Whether you'd like to book or just have a question — fill in the form below and we'll get back to you within 24 hours.": 'Ob Sie buchen möchten oder einfach eine Frage haben — füllen Sie das untenstehende Formular aus, und wir melden uns innerhalb von 24 Stunden bei Ihnen.',
    '📅 Booking Enquiry': '📅 Buchungsanfrage',
    '💬 General Message': '💬 Allgemeine Nachricht',
    'Select Rooms / Apartment': 'Zimmer / Apartment auswählen',
    '* Rooms: max 2 guests per room · infants not accommodated (out of consideration for neighbouring guests). Apartment: up to 4 guests total — 2 included in base rate, up to 2 extra on sofa bed at +€50/person/night.': '* Zimmer: max. 2 Gäste pro Zimmer · Kleinkinder können nicht untergebracht werden (aus Rücksicht auf benachbarte Gäste). Apartment: bis zu 4 Gäste insgesamt — 2 im Grundpreis inbegriffen, bis zu 2 zusätzliche auf dem Schlafsofa für +50 €/Person/Nacht.',
    'Extra Guests — Sofa Bed (Studio Apartment)': 'Zusätzliche Gäste — Schlafsofa (Studio-Apartment)',
    'No extra guests (2 persons included in base rate)': 'Keine zusätzlichen Gäste (2 Personen im Grundpreis inbegriffen)',
    '1 extra guest on sofa bed (+€50 per night)': '1 zusätzlicher Gast auf dem Schlafsofa (+50 € pro Nacht)',
    '2 extra guests on sofa bed (+€100 per night)': '2 zusätzliche Gäste auf dem Schlafsofa (+100 € pro Nacht)',
    'Maximum 4 persons total in the apartment. Extra guests sleep on the sofa bed.': 'Maximal 4 Personen insgesamt im Apartment. Zusätzliche Gäste schlafen auf dem Schlafsofa.',
    'Check-in Date': 'Anreisedatum',
    'Check-out Date': 'Abreisedatum',
    'Estimated Total': 'Geschätzte Gesamtsumme',
    'Select rooms &amp; dates': 'Zimmer &amp; Daten auswählen',
    'Your Name *': 'Ihr Name *',
    'Email *': 'E-Mail *',
    'Phone / WhatsApp': 'Telefon / WhatsApp',
    'Message / Questions': 'Nachricht / Fragen',
    'Confirmation Language': 'Sprache der Bestätigung',
    '(your booking confirmation will be emailed in this language)': '(Ihre Buchungsbestätigung wird in dieser Sprache per E-Mail gesendet)',
    'Español': 'Español',
    'Français': 'Français',
    'Nederlands': 'Nederlands',
    'Send Enquiry': 'Anfrage senden',
    "✅ Your enquiry has been sent! A booking confirmation has been emailed to you and we'll confirm within 24 hours.": '✅ Ihre Anfrage wurde gesendet! Eine Buchungsbestätigung wurde Ihnen per E-Mail zugeschickt, und wir bestätigen innerhalb von 24 Stunden.',
    'Something went wrong. Please email us directly at tamariuchalet@gmail.com': 'Etwas ist schiefgelaufen. Bitte schreiben Sie uns direkt an tamariuchalet@gmail.com',
    '&#x2715;': '&#x2715;',
    'Cancellation Policy': 'Stornierungsbedingungen',
    "We understand that plans can change — here's how we handle cancellations.": 'Wir verstehen, dass sich Pläne ändern können — so handhaben wir Stornierungen.',
    'Cancel 7 days or more before your stay': 'Stornieren Sie 7 Tage oder mehr vor Ihrem Aufenthalt',
    "and we'll refund your payment in full — no questions asked.": 'und wir erstatten Ihre Zahlung vollständig — ohne Wenn und Aber.',
    'We want you to feel confident when you book with us. If something comes up and you need to cancel, simply': 'Wir möchten, dass Sie sich bei der Buchung bei uns sicher fühlen. Falls etwas dazwischenkommt und Sie stornieren müssen, senden Sie uns einfach',
    'send us an email at': 'eine E-Mail an',
    'at least 7 days before your arrival date, and we will arrange a complete refund of any payment made.': 'mindestens 7 Tage vor Ihrem Anreisedatum, und wir veranlassen eine vollständige Erstattung jeder geleisteten Zahlung.',
    'For cancellations made': 'Für Stornierungen, die',
    'within 7 days of arrival': 'innerhalb von 7 Tagen vor Anreise',
    ", we are unfortunately unable to offer a refund, as the accommodation will have been reserved exclusively for you. However, we will always try to work with you if exceptional circumstances arise — so please don't hesitate to get in touch.": 'vorgenommen werden, können wir leider keine Erstattung anbieten, da die Unterkunft exklusiv für Sie reserviert worden sein wird. Wir versuchen jedoch stets, mit Ihnen eine Lösung zu finden, falls außergewöhnliche Umstände eintreten — zögern Sie also bitte nicht, uns zu kontaktieren.',
    'To cancel, please email us with your name, booking dates, and accommodation. We aim to process all refunds within 5 working days.': 'Zum Stornieren senden Sie uns bitte eine E-Mail mit Ihrem Namen, den Buchungsdaten und der Unterkunft. Wir bemühen uns, alle Erstattungen innerhalb von 5 Werktagen zu bearbeiten.',
    'Got It — Close': 'Verstanden — Schließen',
    'Full name': 'Vollständiger Name',
    'your@email.com': 'your@email.com',
    'Any questions, special requirements or additional information...': 'Fragen, besondere Wünsche oder zusätzliche Informationen...',
    'House Rules — Tamariu Chalet': 'Hausordnung — Tamariu Chalet',
    'House Rules': 'Hausordnung',
    'To ensure all guests enjoy a comfortable and relaxing stay, we kindly ask everyone to observe the following house rules. Thank you for your cooperation.': 'Damit alle Gäste einen komfortablen und erholsamen Aufenthalt genießen, bitten wir alle, die folgende Hausordnung zu beachten. Vielen Dank für Ihre Kooperation.',
    '🕓 Check-in &amp; Check-out': '🕓 Check-in &amp; Check-out',
    'Check-in:': 'Check-in:',
    'from 16:00': 'ab 16:00',
    'Check-out:': 'Check-out:',
    'by 10:00': 'bis 10:00',
    'Luggage drop-off is available upon request — please let us know in advance.': 'Gepäckabgabe ist auf Anfrage möglich — bitte teilen Sie uns dies im Voraus mit.',
    '🏊 The Pool': '🏊 Der Pool',
    'The pool is available from mid-June until the end of August.': 'Der Pool ist von Mitte Juni bis Ende August verfügbar.',
    'The pool and gardens are for': 'Der Pool und die Gärten sind',
    'guest use only': 'nur für Gäste',
    'Pool hours:': 'Poolzeiten:',
    'The pool is cleaned and maintained at certain times. When maintenance is in progress please refrain from using the pool — it normally takes no longer than 30 minutes.': 'Der Pool wird zu bestimmten Zeiten gereinigt und gewartet. Während der Wartung sehen Sie bitte von der Nutzung des Pools ab — sie dauert in der Regel nicht länger als 30 Minuten.',
    'Water bed:': 'Wasserbett:',
    'please do not jump onto the water bed as it may burst.': 'bitte springen Sie nicht auf das Wasserbett, da es platzen könnte.',
    'No glassware is permitted in the pool area for safety reasons. Plastic ware is available in the kitchen.': 'Aus Sicherheitsgründen ist im Poolbereich kein Glasgeschirr erlaubt. Plastikgeschirr ist in der Küche verfügbar.',
    '🛏 Rooms': '🛏 Zimmer',
    'Each room has a ceiling fan — please switch it off when you leave the room.': 'Jedes Zimmer hat einen Deckenventilator — bitte schalten Sie ihn aus, wenn Sie das Zimmer verlassen.',
    'No food to be consumed in the rooms as this attracts ants.': 'In den Zimmern dürfen keine Speisen verzehrt werden, da dies Ameisen anzieht.',
    'Each room has a locking door for your privacy and security.': 'Jedes Zimmer hat eine abschließbare Tür für Ihre Privatsphäre und Sicherheit.',
    'All items used should be washed, dried and put away after use.': 'Alle benutzten Gegenstände sollten nach Gebrauch gewaschen, getrocknet und weggeräumt werden.',
    'The hob is available for guests to use. The oven is not available.': 'Das Kochfeld steht den Gästen zur Verfügung. Der Backofen steht nicht zur Verfügung.',
    '🚿 Bathrooms': '🚿 Badezimmer',
    'Please leave the bathrooms as you would like to find them. There should always be soap, shower gel, shampoo and toilet paper available. If any of these run out, please inform the hosts and they will be replenished promptly.': 'Bitte hinterlassen Sie die Badezimmer so, wie Sie sie vorfinden möchten. Es sollten stets Seife, Duschgel, Shampoo und Toilettenpapier vorhanden sein. Sollte etwas davon zur Neige gehen, informieren Sie bitte die Gastgeber, und es wird umgehend nachgefüllt.',
    '🌿 The Garden': '🌿 Der Garten',
    'The garden is available throughout the day and is a shared resource. We ask that you respect other guests and our neighbours by keeping noise to an acceptable level at all times.': 'Der Garten ist den ganzen Tag über verfügbar und wird gemeinschaftlich genutzt. Wir bitten Sie, andere Gäste und unsere Nachbarn zu respektieren, indem Sie den Geräuschpegel jederzeit auf einem akzeptablen Niveau halten.',
    '🍽 Indoor Dining Area': '🍽 Essbereich im Innenbereich',
    'The indoor dining area is available when weather prevents outdoor dining.': 'Der Essbereich im Innenbereich steht zur Verfügung, wenn das Wetter das Essen im Freien verhindert.',
    '🧊 Hallway Refrigerator': '🧊 Kühlschrank im Flur',
    'The hallway refrigerator is available for all guests. A dedicated shelf will be assigned to your room. The remaining shared space is available for general use.': 'Der Kühlschrank im Flur steht allen Gästen zur Verfügung. Ihrem Zimmer wird ein eigenes Fach zugewiesen. Der übrige gemeinsame Platz steht zur allgemeinen Nutzung bereit.',
    '♻️ Waste': '♻️ Abfall',
    'There is a waste basket in the hallway for': 'Im Flur steht ein Abfalleimer für',
    'plastic bottles only': 'nur Plastikflaschen',
    '. Please use the appropriate bins for all other waste.': '. Bitte nutzen Sie für allen anderen Abfall die entsprechenden Behälter.',
    '🗺 Tourist Information': '🗺 Touristeninformation',
    'We provide a selection of tourist information pamphlets and books. Feel free to photograph and use this information. Please leave the books and leaflets on the table for other guests. Copies can also be obtained at the tourist information kiosk in Tamariu.': 'Wir stellen eine Auswahl an touristischen Informationsbroschüren und Büchern bereit. Sie können diese Informationen gern fotografieren und nutzen. Bitte lassen Sie die Bücher und Broschüren für andere Gäste auf dem Tisch liegen. Exemplare sind auch am Touristeninformationskiosk in Tamariu erhältlich.',
    '🧺 Washing Facilities': '🧺 Waschmöglichkeiten',
    'A washing machine is available at a cost of': 'Eine Waschmaschine ist verfügbar zum Preis von',
    '€5 per load': '5 € pro Ladung',
    ', including washing powder.': ', einschließlich Waschpulver.',
    'Drying facilities are available at the side of the house.': 'Trockenmöglichkeiten befinden sich an der Seite des Hauses.',
    '👔 Ironing Facilities': '👔 Bügelmöglichkeiten',
    'Ironing facilities are available on request — please ask the hosts.': 'Bügelmöglichkeiten sind auf Anfrage verfügbar — bitte fragen Sie die Gastgeber.',
    '🌙 Returning Late': '🌙 Spätes Zurückkommen',
    'You are welcome to stay out as late as you like. When you return, please respect other guests and the hosts by keeping noise to a minimum.': 'Sie können gern so lange ausbleiben, wie Sie möchten. Wenn Sie zurückkehren, respektieren Sie bitte andere Gäste und die Gastgeber, indem Sie den Lärm auf ein Minimum reduzieren.',
}
